<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title id="head-title">chz.html</title>
      <link href="assets/style.css" rel="stylesheet" type="text/css"/>
  </head>
  <body>
    <h1 id="title">chz.html</h1>
    <p>Report generated on 02-Feb-2024 at 18:56:16 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a>
        v4.1.1</p>
    <div id="environment-header">
      <h2>Environment</h2>
    </div>
    <table id="environment"></table>
    <!-- TEMPLATES -->
      <template id="template_environment_row">
      <tr>
        <td></td>
        <td></td>
      </tr>
    </template>
    <template id="template_results-table__body--empty">
      <tbody class="results-table-row">
        <tr id="not-found-message">
          <td colspan="4">No results found. Check the filters.</th>
        </tr>
    </template>
    <template id="template_results-table__tbody">
      <tbody class="results-table-row">
        <tr class="collapsible">
        </tr>
        <tr class="extras-row">
          <td class="extra" colspan="4">
            <div class="extraHTML"></div>
            <div class="media">
              <div class="media-container">
                  <div class="media-container__nav--left"><</div>
                  <div class="media-container__viewport">
                    <img src="" />
                    <video controls>
                      <source src="" type="video/mp4">
                    </video>
                  </div>
                  <div class="media-container__nav--right">></div>
                </div>
                <div class="media__name"></div>
                <div class="media__counter"></div>
            </div>
            <div class="logwrapper">
              <div class="logexpander"></div>
              <div class="log"></div>
            </div>
          </td>
        </tr>
      </tbody>
    </template>
    <!-- END TEMPLATES -->
    <div class="summary">
      <div class="summary__data">
        <h2>Summary</h2>
        <div class="additional-summary prefix">
        </div>
        <p class="run-count">66 tests took 00:11:01.</p>
        <p class="filter">(Un)check the boxes to filter the results.</p>
        <div class="summary__reload">
          <div class="summary__reload__button hidden" onclick="location.reload()">
            <div>There are still tests running. <br />Reload this page to get the latest results!</div>
          </div>
        </div>
        <div class="summary__spacer"></div>
        <div class="controls">
          <div class="filters">
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="failed" disabled/>
            <span class="failed">0 Failed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="passed" />
            <span class="passed">66 Passed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="skipped" />
            <span class="skipped">4 Skipped,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xfailed" disabled/>
            <span class="xfailed">0 Expected failures,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xpassed" disabled/>
            <span class="xpassed">0 Unexpected passes,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="error" disabled/>
            <span class="error">0 Errors,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="rerun" disabled/>
            <span class="rerun">0 Reruns</span>
          </div>
          <div class="collapse">
            <button id="show_all_details">Show all details</button>&nbsp;/&nbsp;<button id="hide_all_details">Hide all details</button>
          </div>
        </div>
      </div>
      <div class="additional-summary summary">
      </div>
      <div class="additional-summary postfix">
      </div>
    </div>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable" data-column-type="result">Result</th>
          <th class="sortable" data-column-type="testId">Test</th>
          <th class="sortable" data-column-type="duration">Duration</th>
          <th>Links</th>
        </tr>
      </thead>
    </table>
  </body>
  <footer>
    <div id="data-container" data-jsonblob="{&#34;environment&#34;: {&#34;Python&#34;: &#34;3.9.6&#34;, &#34;Platform&#34;: &#34;macOS-14.3-arm64-arm-64bit&#34;, &#34;Packages&#34;: {&#34;pytest&#34;: &#34;7.4.2&#34;, &#34;pluggy&#34;: &#34;1.3.0&#34;}, &#34;Plugins&#34;: {&#34;html&#34;: &#34;4.1.1&#34;, &#34;mpl&#34;: &#34;0.16.1&#34;, &#34;metadata&#34;: &#34;3.0.0&#34;, &#34;json&#34;: &#34;0.4.0&#34;}}, &#34;tests&#34;: {&#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:08&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:08&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1115e1a60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7149b96c-27a4-4d9f-81de-58c0c72bb69b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e190&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7149b96c-27a4-4d9f-81de-58c0c72bb69b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7149b96c-27a4-4d9f-81de-58c0c72bb69b&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2519b10d-a6dc-4d19-981e-cd5065a3358a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2519b10d-a6dc-4d19-981e-cd5065a3358a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e3a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2519b10d-a6dc-4d19-981e-cd5065a3358a&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114975130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ae422eb-8ee1-46e4-ada9-c5032c3f8f58\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114975700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ae422eb-8ee1-46e4-ada9-c5032c3f8f58\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114975520&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ae422eb-8ee1-46e4-ada9-c5032c3f8f58&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a5ebebd0-85e6-4f1b-816e-2a43cd53f955\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a5ebebd0-85e6-4f1b-816e-2a43cd53f955\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114975610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a5ebebd0-85e6-4f1b-816e-2a43cd53f955&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e040&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/319c9c04-e302-4ae5-8fc4-4db9f05983b7\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1115e1fa0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/319c9c04-e302-4ae5-8fc4-4db9f05983b7\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1115e1fd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/319c9c04-e302-4ae5-8fc4-4db9f05983b7&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987a60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/74892854-37a3-4151-901c-78cca2fe3def\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987ac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/74892854-37a3-4151-901c-78cca2fe3def\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987d30&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/74892854-37a3-4151-901c-78cca2fe3def&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:29&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:29&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987cd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1925b7d7-bf65-47e6-ae09-d4b10530a49e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987ee0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1925b7d7-bf65-47e6-ae09-d4b10530a49e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1925b7d7-bf65-47e6-ae09-d4b10530a49e&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:29&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:29&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114995880&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1f9c9e52-8a7a-4f34-8cd1-6836318b1302\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149958b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1f9c9e52-8a7a-4f34-8cd1-6836318b1302\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114995670&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1f9c9e52-8a7a-4f34-8cd1-6836318b1302&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:98 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...cheezdev.com/&amp;#x27; == &amp;#x27;failblog.cheezdev.com/&amp;#x27;\n  - failblog.cheezdev.com/\n  + https://failblog.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a0169c1d-ee62-4171-8bef-2c3d9fe59925\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a0169c1d-ee62-4171-8bef-2c3d9fe59925\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114995100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a0169c1d-ee62-4171-8bef-2c3d9fe59925&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:110 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...ezburger.com/&amp;#x27; == &amp;#x27;failblog.cheezburger.com/&amp;#x27;\n  - failblog.cheezburger.com/\n  + https://failblog.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987c10&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e623b5f7-438d-487c-8914-f87a64805f1c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e623b5f7-438d-487c-8914-f87a64805f1c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e623b5f7-438d-487c-8914-f87a64805f1c&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4ca0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/396af0bd-24fe-4990-9964-2552764e9af2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149ba070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/396af0bd-24fe-4990-9964-2552764e9af2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149ba1f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/396af0bd-24fe-4990-9964-2552764e9af2&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6398f8f4-fdad-4512-983f-d955f47dc86d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6398f8f4-fdad-4512-983f-d955f47dc86d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e4f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6398f8f4-fdad-4512-983f-d955f47dc86d&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149bab80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/757af7aa-6258-4bcd-8856-4bb76cead7c4\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149bacd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/757af7aa-6258-4bcd-8856-4bb76cead7c4\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149bad00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/757af7aa-6258-4bcd-8856-4bb76cead7c4&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;, &#34;duration&#34;: &#34;00:00:08&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:08&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149c9340&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8c953156-4e1a-4a70-8666-2615f7a68b2c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149c95b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8c953156-4e1a-4a70-8666-2615f7a68b2c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149c9970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8c953156-4e1a-4a70-8666-2615f7a68b2c&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;, &#34;duration&#34;: &#34;00:00:08&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:08&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/adcc68e9-2fdb-4201-a041-1788cb150a40\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/adcc68e9-2fdb-4201-a041-1788cb150a40\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4370&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/adcc68e9-2fdb-4201-a041-1788cb150a40&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149d6100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fc541ff9-37c5-4d07-ba42-629083c2ba1f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149d62e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fc541ff9-37c5-4d07-ba42-629083c2ba1f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149d6580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fc541ff9-37c5-4d07-ba42-629083c2ba1f&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e250&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2e84a5ff-69f6-4390-b269-f23b93d986a4\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11494e070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2e84a5ff-69f6-4390-b269-f23b93d986a4\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149bac10&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2e84a5ff-69f6-4390-b269-f23b93d986a4&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987ac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d4c75ba2-ec89-44ca-87da-9dc1540acf1f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149d60d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d4c75ba2-ec89-44ca-87da-9dc1540acf1f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149d6070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d4c75ba2-ec89-44ca-87da-9dc1540acf1f&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/fail_blog/test_main_desktop.py&amp;#x27;, 167, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/fail_blog/test_main_desktop.py&amp;#x27;, 181, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149e3520&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3ac6dbbe-b74c-4c59-a50b-fd95bbd47d98\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149e3160&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3ac6dbbe-b74c-4c59-a50b-fd95bbd47d98\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149e32b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3ac6dbbe-b74c-4c59-a50b-fd95bbd47d98&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149c9f40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a7911da2-c0be-41bc-ad67-027aee721142\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149c98e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a7911da2-c0be-41bc-ad67-027aee721142\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149c96d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a7911da2-c0be-41bc-ad67-027aee721142&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4040&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/56872692-1adc-4161-8f0a-ff3ad18c3de7\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a43d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/56872692-1adc-4161-8f0a-ff3ad18c3de7\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987ac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/56872692-1adc-4161-8f0a-ff3ad18c3de7&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5fe84437-7238-44e6-9a72-5e9005a6fbc2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5fe84437-7238-44e6-9a72-5e9005a6fbc2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149c9970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5fe84437-7238-44e6-9a72-5e9005a6fbc2&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149e3460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a6992e3a-d400-43d2-8d00-5ffe9e82cf9e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149e3550&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a6992e3a-d400-43d2-8d00-5ffe9e82cf9e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149e3340&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a6992e3a-d400-43d2-8d00-5ffe9e82cf9e&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149f9730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c8a22bc1-453c-4bfd-a055-c6c5bceb923b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149f9be0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c8a22bc1-453c-4bfd-a055-c6c5bceb923b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149f9970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c8a22bc1-453c-4bfd-a055-c6c5bceb923b&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:08&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:08&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149e3730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0ffcf715-d610-4f98-8237-fe0c5b990ccb\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149e3610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0ffcf715-d610-4f98-8237-fe0c5b990ccb\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149e3580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0ffcf715-d610-4f98-8237-fe0c5b990ccb&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:29&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:29&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/633c0ba4-41e9-44fb-ac4e-ed077c20f27e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114987e50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/633c0ba4-41e9-44fb-ac4e-ed077c20f27e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a07220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/633c0ba4-41e9-44fb-ac4e-ed077c20f27e&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:98 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...cheezdev.com/&amp;#x27; == &amp;#x27;urls.icanhas_stage&amp;#x27;\n  - urls.icanhas_stage\n  + https://icanhas.cheezdev.com/\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a07940&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cdb8470a-6b31-440a-97fc-16827d4250ec\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a07dc0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cdb8470a-6b31-440a-97fc-16827d4250ec\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a07b80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cdb8470a-6b31-440a-97fc-16827d4250ec&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:110 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...ezburger.com/&amp;#x27; == &amp;#x27;icanhas.cheezburger.com/&amp;#x27;\n  - icanhas.cheezburger.com/\n  + https://icanhas.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a07a90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fe90fd20-ded2-4ca0-b230-c5623361396d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a070d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fe90fd20-ded2-4ca0-b230-c5623361396d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149a4220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fe90fd20-ded2-4ca0-b230-c5623361396d&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149f99a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4bbdb043-9160-4e3d-b37a-b821ec205d32\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a153d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4bbdb043-9160-4e3d-b37a-b821ec205d32\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a150a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4bbdb043-9160-4e3d-b37a-b821ec205d32&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a15b20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e480d9bf-3aa8-4274-acf4-e6292da326b1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a15a00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e480d9bf-3aa8-4274-acf4-e6292da326b1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a250a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e480d9bf-3aa8-4274-acf4-e6292da326b1&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a15c70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2f09523c-3dfc-4503-b7d5-1dfccbe2243f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149f98b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2f09523c-3dfc-4503-b7d5-1dfccbe2243f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1149f98e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2f09523c-3dfc-4503-b7d5-1dfccbe2243f&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a25490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ecbe9fc6-7e12-43ac-910b-106dd3a364f6\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a255e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ecbe9fc6-7e12-43ac-910b-106dd3a364f6\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a25160&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ecbe9fc6-7e12-43ac-910b-106dd3a364f6&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;, &#34;duration&#34;: &#34;00:00:09&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:09&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a25d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c339e654-3002-4ec1-a0c9-83cf51f39be1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a300d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c339e654-3002-4ec1-a0c9-83cf51f39be1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c339e654-3002-4ec1-a0c9-83cf51f39be1&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a256d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ae3ef71a-f5a6-4470-919f-7a06e9b3f8af\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a250a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ae3ef71a-f5a6-4470-919f-7a06e9b3f8af\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a25730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ae3ef71a-f5a6-4470-919f-7a06e9b3f8af&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30370&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4653ba5d-9b6f-4436-b556-3247f8157002\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30f40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4653ba5d-9b6f-4436-b556-3247f8157002\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30fd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4653ba5d-9b6f-4436-b556-3247f8157002&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fe6b6be3-ddb6-4927-b218-e8eee06ce9f1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30400&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fe6b6be3-ddb6-4927-b218-e8eee06ce9f1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fe6b6be3-ddb6-4927-b218-e8eee06ce9f1&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/icanhas/test_main_desktop.py&amp;#x27;, 167, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/icanhas/test_main_desktop.py&amp;#x27;, 181, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a43490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/bcd8a7b9-e23e-41b0-bd3d-2e30c4c62da3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a43ac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/bcd8a7b9-e23e-41b0-bd3d-2e30c4c62da3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a43910&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/bcd8a7b9-e23e-41b0-bd3d-2e30c4c62da3&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a43610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/87024492-f4c5-4386-b4ba-9cc73625cf85\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a43490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/87024492-f4c5-4386-b4ba-9cc73625cf85\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11159daf0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/87024492-f4c5-4386-b4ba-9cc73625cf85&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9fc20d9b-b5e6-40aa-89b0-97ba34bf3008\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9fc20d9b-b5e6-40aa-89b0-97ba34bf3008\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9fc20d9b-b5e6-40aa-89b0-97ba34bf3008&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a4c760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3af1465d-9953-4ab9-8f5d-e520119f4e06\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a4cd00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3af1465d-9953-4ab9-8f5d-e520119f4e06\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a4cb50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3af1465d-9953-4ab9-8f5d-e520119f4e06&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a4cc40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7ab0e92f-397c-441e-aed1-6e7028530637\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a4c700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7ab0e92f-397c-441e-aed1-6e7028530637\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a30190&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7ab0e92f-397c-441e-aed1-6e7028530637&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a43b20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5e9bef3a-62c3-4935-bbd6-30ddd0c57713\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a43880&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5e9bef3a-62c3-4935-bbd6-30ddd0c57713\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a43970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5e9bef3a-62c3-4935-bbd6-30ddd0c57713&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:35&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:35&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a5f910&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e1bd9a57-4f4e-4bd2-b18f-2bc89e00d555\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a5fd90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e1bd9a57-4f4e-4bd2-b18f-2bc89e00d555\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a5fca0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e1bd9a57-4f4e-4bd2-b18f-2bc89e00d555&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:35&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:35&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a308e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3cd6cb48-5e3f-4d77-ace0-ac61b8f7556a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a4c910&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3cd6cb48-5e3f-4d77-ace0-ac61b8f7556a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a4caf0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3cd6cb48-5e3f-4d77-ace0-ac61b8f7556a&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:97 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...cheezdev.com/&amp;#x27; == &amp;#x27;failblog.cheezdev.com/&amp;#x27;\n  - failblog.cheezdev.com/\n  + https://failblog.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a6f4f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9c7065b5-0e87-4c94-a880-ad75809bf4dd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a6f970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9c7065b5-0e87-4c94-a880-ad75809bf4dd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a6f730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9c7065b5-0e87-4c94-a880-ad75809bf4dd&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:109 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...ezburger.com/&amp;#x27; == &amp;#x27;failblog.cheezburger.com/&amp;#x27;\n  - failblog.cheezburger.com/\n  + https://failblog.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a6f970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7338dd11-195d-4dff-872b-fc0beb2042cb\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a6f520&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7338dd11-195d-4dff-872b-fc0beb2042cb\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a6f940&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7338dd11-195d-4dff-872b-fc0beb2042cb&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:121 Assertion failed: Unexpected URL after scrolling up on the page\nassert &amp;#x27;https://fail...cheezdev.com/&amp;#x27; == &amp;#x27;failblog.cheezdev.com/&amp;#x27;\n  - failblog.cheezdev.com/\n  + https://failblog.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d670&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/960608f1-207e-41b4-b5db-60abcd4f8491\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/960608f1-207e-41b4-b5db-60abcd4f8491\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/960608f1-207e-41b4-b5db-60abcd4f8491&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:133 Assertion failed: Unexpected URL after scrolling up on the page\nassert &amp;#x27;https://fail...ezburger.com/&amp;#x27; == &amp;#x27;failblog.cheezburger.com/&amp;#x27;\n  - failblog.cheezburger.com/\n  + https://failblog.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a8c040&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fb9c0f34-3dc0-47de-bc55-e236a6f52583\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a8c1c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fb9c0f34-3dc0-47de-bc55-e236a6f52583\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a8c340&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fb9c0f34-3dc0-47de-bc55-e236a6f52583&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d160&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0b3faf02-7de4-4ed9-aed0-bcec8d361a08\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d6a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0b3faf02-7de4-4ed9-aed0-bcec8d361a08\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d3d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0b3faf02-7de4-4ed9-aed0-bcec8d361a08&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a8c550&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/bca37452-dc5f-4975-b72e-60a13e6ba930\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a8c7f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/bca37452-dc5f-4975-b72e-60a13e6ba930\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a8cdc0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/bca37452-dc5f-4975-b72e-60a13e6ba930&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;----------------------------- Captured stdout call -----------------------------\nError during execution: Message: Unable to locate element: body.mu-ichc.mu-Channel.language-english.mu-theme-light; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\ndom.find/&amp;lt;/&amp;lt;@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d2b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2b9cfbf7-ca73-4c15-9532-37ce60f934fd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d4f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2b9cfbf7-ca73-4c15-9532-37ce60f934fd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d1f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2b9cfbf7-ca73-4c15-9532-37ce60f934fd&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a8c760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fe6c4cc0-db63-496c-acc6-de97e91c3271\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a8c310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fe6c4cc0-db63-496c-acc6-de97e91c3271\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a8c640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fe6c4cc0-db63-496c-acc6-de97e91c3271&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a9da00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3ede5d1c-b787-440f-aa06-ea2c93f1f346\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a9d700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3ede5d1c-b787-440f-aa06-ea2c93f1f346\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a9d490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3ede5d1c-b787-440f-aa06-ea2c93f1f346&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a9d850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b4750537-f7f6-4c11-92b3-d6ef9d4acaf7\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a9daf0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b4750537-f7f6-4c11-92b3-d6ef9d4acaf7\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a5ffa0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b4750537-f7f6-4c11-92b3-d6ef9d4acaf7&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d6a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b0d4ffb9-0bd7-4121-b43b-4a833551e401\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b0d4ffb9-0bd7-4121-b43b-4a833551e401\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d7c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b0d4ffb9-0bd7-4121-b43b-4a833551e401&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114aa9610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e02a8641-8dec-45dd-9071-e6969399d943\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114aa9ac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e02a8641-8dec-45dd-9071-e6969399d943\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114aa9850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e02a8641-8dec-45dd-9071-e6969399d943&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114aa9ac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7a7eb2f3-b077-42d2-a4ae-d9306eebdf03\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d2e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7a7eb2f3-b077-42d2-a4ae-d9306eebdf03\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7a7eb2f3-b077-42d2-a4ae-d9306eebdf03&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a9d6d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/483c9242-eda7-4053-9461-36746b75bc97\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a9d580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/483c9242-eda7-4053-9461-36746b75bc97\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114aba070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/483c9242-eda7-4053-9461-36746b75bc97&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:35&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:35&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114aba850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ac515bb-e418-4b9e-9645-4f042c2477ce\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114abaf40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ac515bb-e418-4b9e-9645-4f042c2477ce\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114abaf10&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ac515bb-e418-4b9e-9645-4f042c2477ce&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:97 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...cheezdev.com/&amp;#x27; == &amp;#x27;icanhas.cheezdev.com/&amp;#x27;\n  - icanhas.cheezdev.com/\n  + https://icanhas.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d7c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c88d39ec-d7fc-49d2-90e3-4e38416ba955\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c88d39ec-d7fc-49d2-90e3-4e38416ba955\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114a7d6a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c88d39ec-d7fc-49d2-90e3-4e38416ba955&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:109 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...ezburger.com/&amp;#x27; == &amp;#x27;icanhas.cheezburger.com/&amp;#x27;\n  - icanhas.cheezburger.com/\n  + https://icanhas.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ac8430&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/551d98fb-5719-467b-8c28-9b48624548c9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ac88b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/551d98fb-5719-467b-8c28-9b48624548c9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ac8670&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/551d98fb-5719-467b-8c28-9b48624548c9&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:123 Assertion failed: URL inesperada despu\u00e9s de desplazarse hacia arriba en la p\u00e1gina \nassert &amp;#x27;https://ican...cheezdev.com/&amp;#x27; == &amp;#x27;icanhas.cheezdev.com/&amp;#x27;\n  - icanhas.cheezdev.com/\n  + https://icanhas.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ac8b80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dcdc9fac-91ec-4436-a84e-dcda9be30d82\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ac8310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dcdc9fac-91ec-4436-a84e-dcda9be30d82\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ac8580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dcdc9fac-91ec-4436-a84e-dcda9be30d82&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:137 Assertion failed: URL inesperada despu\u00e9s de desplazarse hacia arriba en la p\u00e1gina \nassert &amp;#x27;https://ican...ezburger.com/&amp;#x27; == &amp;#x27;icanhas.cheezburger.com/&amp;#x27;\n  - icanhas.cheezburger.com/\n  + https://icanhas.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ad45b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1d288372-55d3-43ac-9723-0b1ee37f817f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ad44f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1d288372-55d3-43ac-9723-0b1ee37f817f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ad40a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1d288372-55d3-43ac-9723-0b1ee37f817f&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ad4700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9f97155f-4b93-4412-9f73-a4de1e6189b9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ad42e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9f97155f-4b93-4412-9f73-a4de1e6189b9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ad40a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9f97155f-4b93-4412-9f73-a4de1e6189b9&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ac8580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cb815b78-608d-45e9-8aa4-adbb43fafe3d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ac85b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cb815b78-608d-45e9-8aa4-adbb43fafe3d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ae5100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cb815b78-608d-45e9-8aa4-adbb43fafe3d&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;----------------------------- Captured stdout call -----------------------------\nError during execution: Message: Unable to locate element: body.mu-ichc.mu-Channel.language-english.mu-theme-light; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\ndom.find/&amp;lt;/&amp;lt;@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ae58e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/97944fcc-3c96-4c27-b1f8-0e017dd3aa6f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ae5e80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/97944fcc-3c96-4c27-b1f8-0e017dd3aa6f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x114ae5cd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/97944fcc-3c96-4c27-b1f8-0e017dd3aa6f&#34;}]}, &#34;renderCollapsed&#34;: [&#34;passed&#34;], &#34;initialSort&#34;: &#34;result&#34;, &#34;title&#34;: &#34;chz.html&#34;}"></div>
    <script>
      (function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
const { getCollapsedCategory, setCollapsedIds } = require('./storage.js')

class DataManager {
    setManager(data) {
        const collapsedCategories = [...getCollapsedCategory(data.renderCollapsed)]
        const collapsedIds = []
        const tests = Object.values(data.tests).flat().map((test, index) => {
            const collapsed = collapsedCategories.includes(test.result.toLowerCase())
            const id = `test_${index}`
            if (collapsed) {
                collapsedIds.push(id)
            }
            return {
                ...test,
                id,
                collapsed,
            }
        })
        const dataBlob = { ...data, tests }
        this.data = { ...dataBlob }
        this.renderData = { ...dataBlob }
        setCollapsedIds(collapsedIds)
    }

    get allData() {
        return { ...this.data }
    }

    resetRender() {
        this.renderData = { ...this.data }
    }

    setRender(data) {
        this.renderData.tests = [...data]
    }

    toggleCollapsedItem(id) {
        this.renderData.tests = this.renderData.tests.map((test) =>
            test.id === id ? { ...test, collapsed: !test.collapsed } : test,
        )
    }

    set allCollapsed(collapsed) {
        this.renderData = { ...this.renderData, tests: [...this.renderData.tests.map((test) => (
            { ...test, collapsed }
        ))] }
    }

    get testSubset() {
        return [...this.renderData.tests]
    }

    get environment() {
        return this.renderData.environment
    }

    get initialSort() {
        return this.data.initialSort
    }
}

module.exports = {
    manager: new DataManager(),
}

},{"./storage.js":8}],2:[function(require,module,exports){
const mediaViewer = require('./mediaviewer.js')
const templateEnvRow = document.getElementById('template_environment_row')
const templateResult = document.getElementById('template_results-table__tbody')

function htmlToElements(html) {
    const temp = document.createElement('template')
    temp.innerHTML = html
    return temp.content.childNodes
}

const find = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return elem.querySelector(selector)
}

const findAll = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return [...elem.querySelectorAll(selector)]
}

const dom = {
    getStaticRow: (key, value) => {
        const envRow = templateEnvRow.content.cloneNode(true)
        const isObj = typeof value === 'object' && value !== null
        const values = isObj ? Object.keys(value).map((k) => `${k}: ${value[k]}`) : null

        const valuesElement = htmlToElements(
            values ? `<ul>${values.map((val) => `<li>${val}</li>`).join('')}<ul>` : `<div>${value}</div>`)[0]
        const td = findAll('td', envRow)
        td[0].textContent = key
        td[1].appendChild(valuesElement)

        return envRow
    },
    getResultTBody: ({ testId, id, log, extras, resultsTableRow, tableHtml, result, collapsed }) => {
        const resultBody = templateResult.content.cloneNode(true)
        resultBody.querySelector('tbody').classList.add(result.toLowerCase())
        resultBody.querySelector('tbody').id = testId
        resultBody.querySelector('.collapsible').dataset.id = id

        resultsTableRow.forEach((html) => {
            const t = document.createElement('template')
            t.innerHTML = html
            resultBody.querySelector('.collapsible').appendChild(t.content)
        })

        if (log) {
            // Wrap lines starting with "E" with span.error to color those lines red
            const wrappedLog = log.replace(/^E.*$/gm, (match) => `<span class="error">${match}</span>`)
            resultBody.querySelector('.log').innerHTML = wrappedLog
        } else {
            resultBody.querySelector('.log').remove()
        }

        if (collapsed) {
            resultBody.querySelector('.collapsible > td')?.classList.add('collapsed')
            resultBody.querySelector('.extras-row').classList.add('hidden')
        } else {
            resultBody.querySelector('.collapsible > td')?.classList.remove('collapsed')
        }

        const media = []
        extras?.forEach(({ name, format_type, content }) => {
            if (['image', 'video'].includes(format_type)) {
                media.push({ path: content, name, format_type })
            }

            if (format_type === 'html') {
                resultBody.querySelector('.extraHTML').insertAdjacentHTML('beforeend', `<div>${content}</div>`)
            }
        })
        mediaViewer.setup(resultBody, media)

        // Add custom html from the pytest_html_results_table_html hook
        tableHtml?.forEach((item) => {
            resultBody.querySelector('td[class="extra"]').insertAdjacentHTML('beforeend', item)
        })

        return resultBody
    },
}

module.exports = {
    dom,
    htmlToElements,
    find,
    findAll,
}

},{"./mediaviewer.js":6}],3:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const storageModule = require('./storage.js')

const getFilteredSubSet = (filter) =>
    manager.allData.tests.filter(({ result }) => filter.includes(result.toLowerCase()))

const doInitFilter = () => {
    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)
}

const doFilter = (type, show) => {
    if (show) {
        storageModule.showCategory(type)
    } else {
        storageModule.hideCategory(type)
    }

    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)

    const sortColumn = storageModule.getSort()
    doSort(sortColumn, true)
}

module.exports = {
    doFilter,
    doInitFilter,
}

},{"./datamanager.js":1,"./sort.js":7,"./storage.js":8}],4:[function(require,module,exports){
const { redraw, bindEvents, renderStatic } = require('./main.js')
const { doInitFilter } = require('./filter.js')
const { doInitSort } = require('./sort.js')
const { manager } = require('./datamanager.js')
const data = JSON.parse(document.getElementById('data-container').dataset.jsonblob)

function init() {
    manager.setManager(data)
    doInitFilter()
    doInitSort()
    renderStatic()
    redraw()
    bindEvents()
}

init()

},{"./datamanager.js":1,"./filter.js":3,"./main.js":5,"./sort.js":7}],5:[function(require,module,exports){
const { dom, find, findAll } = require('./dom.js')
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const { doFilter } = require('./filter.js')
const {
    getVisible,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    getSortDirection,
    possibleFilters,
} = require('./storage.js')

const removeChildren = (node) => {
    while (node.firstChild) {
        node.removeChild(node.firstChild)
    }
}

const renderStatic = () => {
    const renderEnvironmentTable = () => {
        const environment = manager.environment
        const rows = Object.keys(environment).map((key) => dom.getStaticRow(key, environment[key]))
        const table = document.getElementById('environment')
        removeChildren(table)
        rows.forEach((row) => table.appendChild(row))
    }
    renderEnvironmentTable()
}

const addItemToggleListener = (elem) => {
    elem.addEventListener('click', ({ target }) => {
        const id = target.parentElement.dataset.id
        manager.toggleCollapsedItem(id)

        const collapsedIds = getCollapsedIds()
        if (collapsedIds.includes(id)) {
            const updated = collapsedIds.filter((item) => item !== id)
            setCollapsedIds(updated)
        } else {
            collapsedIds.push(id)
            setCollapsedIds(collapsedIds)
        }
        redraw()
    })
}

const renderContent = (tests) => {
    const sortAttr = getSort(manager.initialSort)
    const sortAsc = JSON.parse(getSortDirection())
    const rows = tests.map(dom.getResultTBody)
    const table = document.getElementById('results-table')
    const tableHeader = document.getElementById('results-table-head')

    const newTable = document.createElement('table')
    newTable.id = 'results-table'

    // remove all sorting classes and set the relevant
    findAll('.sortable', tableHeader).forEach((elem) => elem.classList.remove('asc', 'desc'))
    tableHeader.querySelector(`.sortable[data-column-type="${sortAttr}"]`)?.classList.add(sortAsc ? 'desc' : 'asc')
    newTable.appendChild(tableHeader)

    if (!rows.length) {
        const emptyTable = document.getElementById('template_results-table__body--empty').content.cloneNode(true)
        newTable.appendChild(emptyTable)
    } else {
        rows.forEach((row) => {
            if (!!row) {
                findAll('.collapsible td:not(.col-links', row).forEach(addItemToggleListener)
                find('.logexpander', row).addEventListener('click',
                    (evt) => evt.target.parentNode.classList.toggle('expanded'),
                )
                newTable.appendChild(row)
            }
        })
    }

    table.replaceWith(newTable)
}

const renderDerived = () => {
    const currentFilter = getVisible()
    possibleFilters.forEach((result) => {
        const input = document.querySelector(`input[data-test-result="${result}"]`)
        input.checked = currentFilter.includes(result)
    })
}

const bindEvents = () => {
    const filterColumn = (evt) => {
        const { target: element } = evt
        const { testResult } = element.dataset

        doFilter(testResult, element.checked)
        const collapsedIds = getCollapsedIds()
        const updated = manager.renderData.tests.map((test) => {
            return {
                ...test,
                collapsed: collapsedIds.includes(test.id),
            }
        })
        manager.setRender(updated)
        redraw()
    }

    const header = document.getElementById('environment-header')
    header.addEventListener('click', () => {
        const table = document.getElementById('environment')
        table.classList.toggle('hidden')
        header.classList.toggle('collapsed')
    })

    findAll('input[name="filter_checkbox"]').forEach((elem) => {
        elem.addEventListener('click', filterColumn)
    })

    findAll('.sortable').forEach((elem) => {
        elem.addEventListener('click', (evt) => {
            const { target: element } = evt
            const { columnType } = element.dataset
            doSort(columnType)
            redraw()
        })
    })

    document.getElementById('show_all_details').addEventListener('click', () => {
        manager.allCollapsed = false
        setCollapsedIds([])
        redraw()
    })
    document.getElementById('hide_all_details').addEventListener('click', () => {
        manager.allCollapsed = true
        const allIds = manager.renderData.tests.map((test) => test.id)
        setCollapsedIds(allIds)
        redraw()
    })
}

const redraw = () => {
    const { testSubset } = manager

    renderContent(testSubset)
    renderDerived()
}

module.exports = {
    redraw,
    bindEvents,
    renderStatic,
}

},{"./datamanager.js":1,"./dom.js":2,"./filter.js":3,"./sort.js":7,"./storage.js":8}],6:[function(require,module,exports){
class MediaViewer {
    constructor(assets) {
        this.assets = assets
        this.index = 0
    }

    nextActive() {
        this.index = this.index === this.assets.length - 1 ? 0 : this.index + 1
        return [this.activeFile, this.index]
    }

    prevActive() {
        this.index = this.index === 0 ? this.assets.length - 1 : this.index -1
        return [this.activeFile, this.index]
    }

    get currentIndex() {
        return this.index
    }

    get activeFile() {
        return this.assets[this.index]
    }
}


const setup = (resultBody, assets) => {
    if (!assets.length) {
        resultBody.querySelector('.media').classList.add('hidden')
        return
    }

    const mediaViewer = new MediaViewer(assets)
    const container = resultBody.querySelector('.media-container')
    const leftArrow = resultBody.querySelector('.media-container__nav--left')
    const rightArrow = resultBody.querySelector('.media-container__nav--right')
    const mediaName = resultBody.querySelector('.media__name')
    const counter = resultBody.querySelector('.media__counter')
    const imageEl = resultBody.querySelector('img')
    const sourceEl = resultBody.querySelector('source')
    const videoEl = resultBody.querySelector('video')

    const setImg = (media, index) => {
        if (media?.format_type === 'image') {
            imageEl.src = media.path

            imageEl.classList.remove('hidden')
            videoEl.classList.add('hidden')
        } else if (media?.format_type === 'video') {
            sourceEl.src = media.path

            videoEl.classList.remove('hidden')
            imageEl.classList.add('hidden')
        }

        mediaName.innerText = media?.name
        counter.innerText = `${index + 1} / ${assets.length}`
    }
    setImg(mediaViewer.activeFile, mediaViewer.currentIndex)

    const moveLeft = () => {
        const [media, index] = mediaViewer.prevActive()
        setImg(media, index)
    }
    const doRight = () => {
        const [media, index] = mediaViewer.nextActive()
        setImg(media, index)
    }
    const openImg = () => {
        window.open(mediaViewer.activeFile.path, '_blank')
    }
    if (assets.length === 1) {
        container.classList.add('media-container--fullscreen')
    } else {
        leftArrow.addEventListener('click', moveLeft)
        rightArrow.addEventListener('click', doRight)
    }
    imageEl.addEventListener('click', openImg)
}

module.exports = {
    setup,
}

},{}],7:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const storageModule = require('./storage.js')

const genericSort = (list, key, ascending, customOrder) => {
    let sorted
    if (customOrder) {
        sorted = list.sort((a, b) => {
            const aValue = a.result.toLowerCase()
            const bValue = b.result.toLowerCase()

            const aIndex = customOrder.findIndex((item) => item.toLowerCase() === aValue)
            const bIndex = customOrder.findIndex((item) => item.toLowerCase() === bValue)

            // Compare the indices to determine the sort order
            return aIndex - bIndex
        })
    } else {
        sorted = list.sort((a, b) => a[key] === b[key] ? 0 : a[key] > b[key] ? 1 : -1)
    }

    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const durationSort = (list, ascending) => {
    const parseDuration = (duration) => {
        if (duration.includes(':')) {
            // If it's in the format "HH:mm:ss"
            const [hours, minutes, seconds] = duration.split(':').map(Number)
            return (hours * 3600 + minutes * 60 + seconds) * 1000
        } else {
            // If it's in the format "nnn ms"
            return parseInt(duration)
        }
    }
    const sorted = list.sort((a, b) => parseDuration(a['duration']) - parseDuration(b['duration']))
    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const doInitSort = () => {
    const type = storageModule.getSort(manager.initialSort)
    const ascending = storageModule.getSortDirection()
    const list = manager.testSubset
    const initialOrder = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed', 'Skipped', 'Passed']

    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    if (type?.toLowerCase() === 'original') {
        manager.setRender(list)
    } else {
        let sortedList
        switch (type) {
        case 'duration':
            sortedList = durationSort(list, ascending)
            break
        case 'result':
            sortedList = genericSort(list, type, ascending, initialOrder)
            break
        default:
            sortedList = genericSort(list, type, ascending)
            break
        }
        manager.setRender(sortedList)
    }
}

const doSort = (type, skipDirection) => {
    const newSortType = storageModule.getSort(manager.initialSort) !== type
    const currentAsc = storageModule.getSortDirection()
    let ascending
    if (skipDirection) {
        ascending = currentAsc
    } else {
        ascending = newSortType ? false : !currentAsc
    }
    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    const list = manager.testSubset
    const sortedList = type === 'duration' ? durationSort(list, ascending) : genericSort(list, type, ascending)
    manager.setRender(sortedList)
}

module.exports = {
    doInitSort,
    doSort,
}

},{"./datamanager.js":1,"./storage.js":8}],8:[function(require,module,exports){
const possibleFilters = [
    'passed',
    'skipped',
    'failed',
    'error',
    'xfailed',
    'xpassed',
    'rerun',
]

const getVisible = () => {
    const url = new URL(window.location.href)
    const settings = new URLSearchParams(url.search).get('visible')
    const lower = (item) => {
        const lowerItem = item.toLowerCase()
        if (possibleFilters.includes(lowerItem)) {
            return lowerItem
        }
        return null
    }
    return settings === null ?
        possibleFilters :
        [...new Set(settings?.split(',').map(lower).filter((item) => item))]
}

const hideCategory = (categoryToHide) => {
    const url = new URL(window.location.href)
    const visibleParams = new URLSearchParams(url.search).get('visible')
    const currentVisible = visibleParams ? visibleParams.split(',') : [...possibleFilters]
    const settings = [...new Set(currentVisible)].filter((f) => f !== categoryToHide).join(',')

    url.searchParams.set('visible', settings)
    window.history.pushState({}, null, unescape(url.href))
}

const showCategory = (categoryToShow) => {
    if (typeof window === 'undefined') {
        return
    }
    const url = new URL(window.location.href)
    const currentVisible = new URLSearchParams(url.search).get('visible')?.split(',').filter(Boolean) ||
        [...possibleFilters]
    const settings = [...new Set([categoryToShow, ...currentVisible])]
    const noFilter = possibleFilters.length === settings.length || !settings.length

    noFilter ? url.searchParams.delete('visible') : url.searchParams.set('visible', settings.join(','))
    window.history.pushState({}, null, unescape(url.href))
}

const getSort = (initialSort) => {
    const url = new URL(window.location.href)
    let sort = new URLSearchParams(url.search).get('sort')
    if (!sort) {
        sort = initialSort || 'result'
    }
    return sort
}

const setSort = (type) => {
    const url = new URL(window.location.href)
    url.searchParams.set('sort', type)
    window.history.pushState({}, null, unescape(url.href))
}

const getCollapsedCategory = (renderCollapsed) => {
    let categories
    if (typeof window !== 'undefined') {
        const url = new URL(window.location.href)
        const collapsedItems = new URLSearchParams(url.search).get('collapsed')
        switch (true) {
        case !renderCollapsed && collapsedItems === null:
            categories = ['passed']
            break
        case collapsedItems?.length === 0 || /^["']{2}$/.test(collapsedItems):
            categories = []
            break
        case /^all$/.test(collapsedItems) || collapsedItems === null && /^all$/.test(renderCollapsed):
            categories = [...possibleFilters]
            break
        default:
            categories = collapsedItems?.split(',').map((item) => item.toLowerCase()) || renderCollapsed
            break
        }
    } else {
        categories = []
    }
    return categories
}

const getSortDirection = () => JSON.parse(sessionStorage.getItem('sortAsc')) || false
const setSortDirection = (ascending) => sessionStorage.setItem('sortAsc', ascending)

const getCollapsedIds = () => JSON.parse(sessionStorage.getItem('collapsedIds')) || []
const setCollapsedIds = (list) => sessionStorage.setItem('collapsedIds', JSON.stringify(list))

module.exports = {
    getVisible,
    hideCategory,
    showCategory,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    setSort,
    getSortDirection,
    setSortDirection,
    getCollapsedCategory,
    possibleFilters,
}

},{}]},{},[4]);
    </script>
  </footer>
</html>