<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title id="head-title">chz.html</title>
      <link href="assets/style.css" rel="stylesheet" type="text/css"/>
  </head>
  <body>
    <h1 id="title">chz.html</h1>
    <p>Report generated on 07-Jun-2024 at 14:58:16 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a>
        v4.1.1</p>
    <div id="environment-header">
      <h2>Environment</h2>
    </div>
    <table id="environment"></table>
    <!-- TEMPLATES -->
      <template id="template_environment_row">
      <tr>
        <td></td>
        <td></td>
      </tr>
    </template>
    <template id="template_results-table__body--empty">
      <tbody class="results-table-row">
        <tr id="not-found-message">
          <td colspan="4">No results found. Check the filters.</th>
        </tr>
    </template>
    <template id="template_results-table__tbody">
      <tbody class="results-table-row">
        <tr class="collapsible">
        </tr>
        <tr class="extras-row">
          <td class="extra" colspan="4">
            <div class="extraHTML"></div>
            <div class="media">
              <div class="media-container">
                  <div class="media-container__nav--left"><</div>
                  <div class="media-container__viewport">
                    <img src="" />
                    <video controls>
                      <source src="" type="video/mp4">
                    </video>
                  </div>
                  <div class="media-container__nav--right">></div>
                </div>
                <div class="media__name"></div>
                <div class="media__counter"></div>
            </div>
            <div class="logwrapper">
              <div class="logexpander"></div>
              <div class="log"></div>
            </div>
          </td>
        </tr>
      </tbody>
    </template>
    <!-- END TEMPLATES -->
    <div class="summary">
      <div class="summary__data">
        <h2>Summary</h2>
        <div class="additional-summary prefix">
        </div>
        <p class="run-count">66 tests took 00:12:01.</p>
        <p class="filter">(Un)check the boxes to filter the results.</p>
        <div class="summary__reload">
          <div class="summary__reload__button hidden" onclick="location.reload()">
            <div>There are still tests running. <br />Reload this page to get the latest results!</div>
          </div>
        </div>
        <div class="summary__spacer"></div>
        <div class="controls">
          <div class="filters">
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="failed" disabled/>
            <span class="failed">0 Failed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="passed" />
            <span class="passed">64 Passed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="skipped" />
            <span class="skipped">4 Skipped,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xfailed" disabled/>
            <span class="xfailed">0 Expected failures,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xpassed" />
            <span class="xpassed">2 Unexpected passes,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="error" disabled/>
            <span class="error">0 Errors,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="rerun" disabled/>
            <span class="rerun">0 Reruns</span>
          </div>
          <div class="collapse">
            <button id="show_all_details">Show all details</button>&nbsp;/&nbsp;<button id="hide_all_details">Hide all details</button>
          </div>
        </div>
      </div>
      <div class="additional-summary summary">
      </div>
      <div class="additional-summary postfix">
      </div>
    </div>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable" data-column-type="result">Result</th>
          <th class="sortable" data-column-type="testId">Test</th>
          <th class="sortable" data-column-type="duration">Duration</th>
          <th>Links</th>
        </tr>
      </thead>
    </table>
  </body>
  <footer>
    <div id="data-container" data-jsonblob="{&#34;environment&#34;: {&#34;Python&#34;: &#34;3.9.6&#34;, &#34;Platform&#34;: &#34;macOS-14.5-arm64-arm-64bit&#34;, &#34;Packages&#34;: {&#34;pytest&#34;: &#34;7.4.2&#34;, &#34;pluggy&#34;: &#34;1.3.0&#34;}, &#34;Plugins&#34;: {&#34;html&#34;: &#34;4.1.1&#34;, &#34;mpl&#34;: &#34;0.16.1&#34;, &#34;metadata&#34;: &#34;3.0.0&#34;, &#34;json&#34;: &#34;0.4.0&#34;}}, &#34;tests&#34;: {&#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x107564d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/77abee91-404a-4da8-8977-94465e7403c2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x107564f40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/77abee91-404a-4da8-8977-94465e7403c2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c2c0a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/77abee91-404a-4da8-8977-94465e7403c2&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x107564d60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/31fd7c1f-2cb3-435f-8c69-a6911de507b5\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c2c580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/31fd7c1f-2cb3-435f-8c69-a6911de507b5\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c2c100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/31fd7c1f-2cb3-435f-8c69-a6911de507b5&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c41070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6646ee33-3563-41ee-a8df-b514db3daeb7\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c41310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6646ee33-3563-41ee-a8df-b514db3daeb7\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c414c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6646ee33-3563-41ee-a8df-b514db3daeb7&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c41bb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/03ed6dc2-269f-4169-a1a6-acba67c1dd24\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c41b80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/03ed6dc2-269f-4169-a1a6-acba67c1dd24\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c41250&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/03ed6dc2-269f-4169-a1a6-acba67c1dd24&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x107564ee0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c06b86ca-37da-48a2-91aa-498164c47f9f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x107564f40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c06b86ca-37da-48a2-91aa-498164c47f9f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x107564c10&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c06b86ca-37da-48a2-91aa-498164c47f9f&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:01:00&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:01:00&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c567c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8b882352-04e2-4a72-8b9a-8ccca8a7da76\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56ca0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8b882352-04e2-4a72-8b9a-8ccca8a7da76\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56b50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8b882352-04e2-4a72-8b9a-8ccca8a7da76&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:27&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:27&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56f10&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b2ae0a1a-9855-4d9d-bb5d-d093552d1a8c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56e80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b2ae0a1a-9855-4d9d-bb5d-d093552d1a8c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b2ae0a1a-9855-4d9d-bb5d-d093552d1a8c&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:27&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:27&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c41250&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8c4ebe1a-f119-4b6c-b46e-f7a3bbc95dfa\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c63610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8c4ebe1a-f119-4b6c-b46e-f7a3bbc95dfa\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c638e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8c4ebe1a-f119-4b6c-b46e-f7a3bbc95dfa&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70280&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4e00f196-56f7-4de6-b581-ae430e4fd1d1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70370&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4e00f196-56f7-4de6-b581-ae430e4fd1d1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4e00f196-56f7-4de6-b581-ae430e4fd1d1&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a4663be9-a0ce-4c56-9c91-90dc65b37fbf\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56eb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a4663be9-a0ce-4c56-9c91-90dc65b37fbf\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c2c850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a4663be9-a0ce-4c56-9c91-90dc65b37fbf&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70bb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/daabf05b-2631-4fa8-9345-5bfbad5495fc\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70df0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/daabf05b-2631-4fa8-9345-5bfbad5495fc\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/daabf05b-2631-4fa8-9345-5bfbad5495fc&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56df0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ef07f0d0-b610-438d-bc83-4e12976869e0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56bb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ef07f0d0-b610-438d-bc83-4e12976869e0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c708e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ef07f0d0-b610-438d-bc83-4e12976869e0&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c82730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/be3a65f3-3670-4080-a5e9-52acb3da18d1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c82c40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/be3a65f3-3670-4080-a5e9-52acb3da18d1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c821f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/be3a65f3-3670-4080-a5e9-52acb3da18d1&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c8e3a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3d2fbda4-a5d1-47e5-a4ae-07d34ff87c86\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c8e5e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3d2fbda4-a5d1-47e5-a4ae-07d34ff87c86\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c8e580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3d2fbda4-a5d1-47e5-a4ae-07d34ff87c86&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;, &#34;duration&#34;: &#34;00:00:09&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:09&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70a00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/57379682-672c-459b-9385-6e63698e7b1c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56d60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/57379682-672c-459b-9385-6e63698e7b1c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c56c40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/57379682-672c-459b-9385-6e63698e7b1c&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c8ed90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/838c14fc-7b9d-43a1-9cbb-6104d44c92f4\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9d280&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/838c14fc-7b9d-43a1-9cbb-6104d44c92f4\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9d310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/838c14fc-7b9d-43a1-9cbb-6104d44c92f4&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70eb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5869cfff-4a8c-459d-8c90-6b8020264756\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c8efa0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5869cfff-4a8c-459d-8c90-6b8020264756\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c8ee80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5869cfff-4a8c-459d-8c90-6b8020264756&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9d220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d8e5c68f-750e-4ec4-980a-ae5b663b3847\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9da90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d8e5c68f-750e-4ec4-980a-ae5b663b3847\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9db50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d8e5c68f-750e-4ec4-980a-ae5b663b3847&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/fail_blog/test_main_desktop.py&amp;#x27;, 241, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/fail_blog/test_main_desktop.py&amp;#x27;, 259, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9dee0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e529d468-5d81-4322-87a1-b5abda9152f5\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9de80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e529d468-5d81-4322-87a1-b5abda9152f5\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9dfa0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e529d468-5d81-4322-87a1-b5abda9152f5&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c8e1c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/de020b3a-7101-4f02-b881-8c881315bf5c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70ee0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/de020b3a-7101-4f02-b881-8c881315bf5c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70e80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/de020b3a-7101-4f02-b881-8c881315bf5c&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c41d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/795d44d5-1e11-497b-aa0a-e165c6c49885\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c41f70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/795d44d5-1e11-497b-aa0a-e165c6c49885\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cb4670&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/795d44d5-1e11-497b-aa0a-e165c6c49885&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70eb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7d926bbd-03b1-493b-92c3-5f0fe55e369e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c708e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7d926bbd-03b1-493b-92c3-5f0fe55e369e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c700a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7d926bbd-03b1-493b-92c3-5f0fe55e369e&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9dee0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cbd47eb4-7a24-4cdd-acb7-533abd828bd9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9de20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cbd47eb4-7a24-4cdd-acb7-533abd828bd9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cb47f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cbd47eb4-7a24-4cdd-acb7-533abd828bd9&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cc8640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/45b858d3-f95a-4317-848b-29532a91b2f3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cc8820&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/45b858d3-f95a-4317-848b-29532a91b2f3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cc8af0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/45b858d3-f95a-4317-848b-29532a91b2f3&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:28&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:28&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c8e220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/59334cec-deeb-43ac-89f5-9b688350f11e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/59334cec-deeb-43ac-89f5-9b688350f11e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/59334cec-deeb-43ac-89f5-9b688350f11e&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:27&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:27&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cc87f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c814ad88-feb2-4167-b2dd-80296b0f238b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cc8610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c814ad88-feb2-4167-b2dd-80296b0f238b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cc8a60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c814ad88-feb2-4167-b2dd-80296b0f238b&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cd7880&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/478450f5-8ef5-4d3f-b203-5f8a7e888ea9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cd7640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/478450f5-8ef5-4d3f-b203-5f8a7e888ea9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cd7bb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/478450f5-8ef5-4d3f-b203-5f8a7e888ea9&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cd7100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a7302143-b36d-4a08-9af7-427e110f5e38\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cc8790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a7302143-b36d-4a08-9af7-427e110f5e38\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cc8a90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a7302143-b36d-4a08-9af7-427e110f5e38&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c70310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b77a8efd-1910-4682-8b86-23fa0f10ad1e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9dee0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b77a8efd-1910-4682-8b86-23fa0f10ad1e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116ce60a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b77a8efd-1910-4682-8b86-23fa0f10ad1e&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116ce6a60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e1690597-225b-4032-8b28-de39645f505f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116ce6e80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e1690597-225b-4032-8b28-de39645f505f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116ce6b80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e1690597-225b-4032-8b28-de39645f505f&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116ce68e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/20445c55-622a-4273-9a88-ba43b153af12\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116ce60d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/20445c55-622a-4273-9a88-ba43b153af12\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116c9dd90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/20445c55-622a-4273-9a88-ba43b153af12&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cd7760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0d1137c1-49f2-4135-a1d9-aab046368adc\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cd78b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0d1137c1-49f2-4135-a1d9-aab046368adc\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cf1370&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0d1137c1-49f2-4135-a1d9-aab046368adc&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;, &#34;duration&#34;: &#34;00:00:09&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:09&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cf1c10&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2c31c167-2439-4227-93f8-9d95775037bb\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cf1d90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2c31c167-2439-4227-93f8-9d95775037bb\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cf1d60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2c31c167-2439-4227-93f8-9d95775037bb&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cf1310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5b3ab910-eddf-4a75-b24b-fd063b2354fe\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cd7160&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5b3ab910-eddf-4a75-b24b-fd063b2354fe\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cd7820&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5b3ab910-eddf-4a75-b24b-fd063b2354fe&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:12&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:12&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116ce6130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ae80be27-d369-4223-a544-ae0b1a34f832\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cfef70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ae80be27-d369-4223-a544-ae0b1a34f832\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cfee20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ae80be27-d369-4223-a544-ae0b1a34f832&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cfe130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ccfff031-8ba7-44a5-93ca-010472eb1d54\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cfe460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ccfff031-8ba7-44a5-93ca-010472eb1d54\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cfed30&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ccfff031-8ba7-44a5-93ca-010472eb1d54&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/icanhas/test_main_desktop.py&amp;#x27;, 271, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/icanhas/test_main_desktop.py&amp;#x27;, 288, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d0c580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f7f41792-eb9a-452e-bd9f-8404a73eb64d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d0c640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f7f41792-eb9a-452e-bd9f-8404a73eb64d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d0c760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f7f41792-eb9a-452e-bd9f-8404a73eb64d&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d0c850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/913a06e4-880e-487b-9ba4-2e70a826bc77\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d0c460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/913a06e4-880e-487b-9ba4-2e70a826bc77\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d0c490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/913a06e4-880e-487b-9ba4-2e70a826bc77&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cfeee0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/37f2281e-986b-4135-8c05-42cae0370e91\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cfe730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/37f2281e-986b-4135-8c05-42cae0370e91\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cfe400&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/37f2281e-986b-4135-8c05-42cae0370e91&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d1d670&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dd83b787-c406-4448-830d-ab5b67442859\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d1d730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dd83b787-c406-4448-830d-ab5b67442859\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d1d850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dd83b787-c406-4448-830d-ab5b67442859&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d1d520&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/820bc903-3a3f-438b-8b02-e6f1d407832b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d1d640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/820bc903-3a3f-438b-8b02-e6f1d407832b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cfe640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/820bc903-3a3f-438b-8b02-e6f1d407832b&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d0cac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6b03873f-750b-4db0-b0fd-dc90f76bfb35\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d0c640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6b03873f-750b-4db0-b0fd-dc90f76bfb35\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d0c3d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6b03873f-750b-4db0-b0fd-dc90f76bfb35&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;XPassed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:34&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;XPassed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:34&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d27820&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1a9483ea-5606-46ae-9704-fa2b91d358fe\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d27ca0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1a9483ea-5606-46ae-9704-fa2b91d358fe\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d27640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1a9483ea-5606-46ae-9704-fa2b91d358fe&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:35&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:35&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116cfeca0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/33d82d97-d17c-475e-a86e-abfbf517b968\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d1d490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/33d82d97-d17c-475e-a86e-abfbf517b968\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d1da00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/33d82d97-d17c-475e-a86e-abfbf517b968&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d36400&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a9f0ad11-f5b4-48c5-937a-59c006beaf55\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d361c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a9f0ad11-f5b4-48c5-937a-59c006beaf55\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d36730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a9f0ad11-f5b4-48c5-937a-59c006beaf55&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d36880&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/206385e4-2bd2-437b-b6ac-4645131445a0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d361c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/206385e4-2bd2-437b-b6ac-4645131445a0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d36220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/206385e4-2bd2-437b-b6ac-4645131445a0&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d4a250&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/57a4ac60-3652-4bd2-aa27-362481476fe0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d4a340&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/57a4ac60-3652-4bd2-aa27-362481476fe0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d4a460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/57a4ac60-3652-4bd2-aa27-362481476fe0&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d4acd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2868ca3f-b02e-4b2f-8e51-89974113ea2b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d4ad60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2868ca3f-b02e-4b2f-8e51-89974113ea2b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d54070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2868ca3f-b02e-4b2f-8e51-89974113ea2b&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:12&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:12&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d4ae20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3a66988e-1dca-434b-9edf-e5c58a3d89fa\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d4abe0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3a66988e-1dca-434b-9edf-e5c58a3d89fa\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d4ad60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3a66988e-1dca-434b-9edf-e5c58a3d89fa&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d36580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0b6ed0fc-9e3e-430e-add1-16eed0ed14df\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d361f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0b6ed0fc-9e3e-430e-add1-16eed0ed14df\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d54f70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0b6ed0fc-9e3e-430e-add1-16eed0ed14df&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;----------------------------- Captured stdout call -----------------------------\nError during execution: Message: Unable to locate element: body.mu-ichc.mu-Channel.language-english.mu-theme-light; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/&amp;lt;/&amp;lt;@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d54be0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dbf63833-caac-4e02-9376-8a6e6b17c9fe\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d610a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dbf63833-caac-4e02-9376-8a6e6b17c9fe\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dbf63833-caac-4e02-9376-8a6e6b17c9fe&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d366d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b91e91e0-5189-4666-a214-c141418f8cb8\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d36310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b91e91e0-5189-4666-a214-c141418f8cb8\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d4abb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b91e91e0-5189-4666-a214-c141418f8cb8&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d278e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/684538c1-adff-4740-a8f6-3ceb151d60d3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d27940&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/684538c1-adff-4740-a8f6-3ceb151d60d3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d27910&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/684538c1-adff-4740-a8f6-3ceb151d60d3&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d619a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/00663054-9173-4c74-9fbd-09b754811cb5\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61a60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/00663054-9173-4c74-9fbd-09b754811cb5\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61b80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/00663054-9173-4c74-9fbd-09b754811cb5&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0e02179c-19b6-4af3-b0c9-63397a82a13a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d618e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0e02179c-19b6-4af3-b0c9-63397a82a13a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61e20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0e02179c-19b6-4af3-b0c9-63397a82a13a&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d362b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7fbd0020-ac4c-4d2e-ad8c-0853ef6f9b4f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d36250&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7fbd0020-ac4c-4d2e-ad8c-0853ef6f9b4f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d364c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7fbd0020-ac4c-4d2e-ad8c-0853ef6f9b4f&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d71bb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e3002cc8-e5bd-4e1a-a79e-496df16376b0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d71eb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e3002cc8-e5bd-4e1a-a79e-496df16376b0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d71a60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e3002cc8-e5bd-4e1a-a79e-496df16376b0&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;XPassed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:33&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;XPassed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:33&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d71f70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/96d0e4b2-164c-4edb-8a62-51c9261b1eec\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d54f70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/96d0e4b2-164c-4edb-8a62-51c9261b1eec\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d366a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/96d0e4b2-164c-4edb-8a62-51c9261b1eec&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:34&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:34&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61b20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e31c55ba-9cd0-4d65-a2bb-6dc1f858f7c5\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61ee0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e31c55ba-9cd0-4d65-a2bb-6dc1f858f7c5\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e31c55ba-9cd0-4d65-a2bb-6dc1f858f7c5&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d80d60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7c3316f5-74ee-4626-91e0-3a884c44596d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d80e80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7c3316f5-74ee-4626-91e0-3a884c44596d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d8e040&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7c3316f5-74ee-4626-91e0-3a884c44596d&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61a60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9614e93c-42ae-4816-8912-f08d4fbf2f5c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9614e93c-42ae-4816-8912-f08d4fbf2f5c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61a30&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9614e93c-42ae-4816-8912-f08d4fbf2f5c&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d8e640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b7279824-4152-48cc-b1bb-18dae793bdac\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d8e7c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b7279824-4152-48cc-b1bb-18dae793bdac\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d8e310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b7279824-4152-48cc-b1bb-18dae793bdac&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d8ed90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ac46d2a-8a48-4d36-a6fe-4dc0dca8c510\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d9c220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ac46d2a-8a48-4d36-a6fe-4dc0dca8c510\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d9c400&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ac46d2a-8a48-4d36-a6fe-4dc0dca8c510&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:12&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:12&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61910&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c1797e3c-0df9-4897-b63a-022c18d40639\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d618b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c1797e3c-0df9-4897-b63a-022c18d40639\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d61cd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c1797e3c-0df9-4897-b63a-022c18d40639&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d9c580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b81cad42-6d96-4e35-b5c7-19404f19d442\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d9caf0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b81cad42-6d96-4e35-b5c7-19404f19d442\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116d9c3d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b81cad42-6d96-4e35-b5c7-19404f19d442&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;----------------------------- Captured stdout call -----------------------------\nError during execution: Message: Unable to locate element: body.mu-ichc.mu-Channel.language-english.mu-theme-light; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/&amp;lt;/&amp;lt;@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116dad340&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6f967b93-1ebb-44a5-af11-7c23d6884f15\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116dad730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6f967b93-1ebb-44a5-af11-7c23d6884f15\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x116dad160&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6f967b93-1ebb-44a5-af11-7c23d6884f15&#34;}]}, &#34;renderCollapsed&#34;: [&#34;passed&#34;], &#34;initialSort&#34;: &#34;result&#34;, &#34;title&#34;: &#34;chz.html&#34;}"></div>
    <script>
      (function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
const { getCollapsedCategory, setCollapsedIds } = require('./storage.js')

class DataManager {
    setManager(data) {
        const collapsedCategories = [...getCollapsedCategory(data.renderCollapsed)]
        const collapsedIds = []
        const tests = Object.values(data.tests).flat().map((test, index) => {
            const collapsed = collapsedCategories.includes(test.result.toLowerCase())
            const id = `test_${index}`
            if (collapsed) {
                collapsedIds.push(id)
            }
            return {
                ...test,
                id,
                collapsed,
            }
        })
        const dataBlob = { ...data, tests }
        this.data = { ...dataBlob }
        this.renderData = { ...dataBlob }
        setCollapsedIds(collapsedIds)
    }

    get allData() {
        return { ...this.data }
    }

    resetRender() {
        this.renderData = { ...this.data }
    }

    setRender(data) {
        this.renderData.tests = [...data]
    }

    toggleCollapsedItem(id) {
        this.renderData.tests = this.renderData.tests.map((test) =>
            test.id === id ? { ...test, collapsed: !test.collapsed } : test,
        )
    }

    set allCollapsed(collapsed) {
        this.renderData = { ...this.renderData, tests: [...this.renderData.tests.map((test) => (
            { ...test, collapsed }
        ))] }
    }

    get testSubset() {
        return [...this.renderData.tests]
    }

    get environment() {
        return this.renderData.environment
    }

    get initialSort() {
        return this.data.initialSort
    }
}

module.exports = {
    manager: new DataManager(),
}

},{"./storage.js":8}],2:[function(require,module,exports){
const mediaViewer = require('./mediaviewer.js')
const templateEnvRow = document.getElementById('template_environment_row')
const templateResult = document.getElementById('template_results-table__tbody')

function htmlToElements(html) {
    const temp = document.createElement('template')
    temp.innerHTML = html
    return temp.content.childNodes
}

const find = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return elem.querySelector(selector)
}

const findAll = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return [...elem.querySelectorAll(selector)]
}

const dom = {
    getStaticRow: (key, value) => {
        const envRow = templateEnvRow.content.cloneNode(true)
        const isObj = typeof value === 'object' && value !== null
        const values = isObj ? Object.keys(value).map((k) => `${k}: ${value[k]}`) : null

        const valuesElement = htmlToElements(
            values ? `<ul>${values.map((val) => `<li>${val}</li>`).join('')}<ul>` : `<div>${value}</div>`)[0]
        const td = findAll('td', envRow)
        td[0].textContent = key
        td[1].appendChild(valuesElement)

        return envRow
    },
    getResultTBody: ({ testId, id, log, extras, resultsTableRow, tableHtml, result, collapsed }) => {
        const resultBody = templateResult.content.cloneNode(true)
        resultBody.querySelector('tbody').classList.add(result.toLowerCase())
        resultBody.querySelector('tbody').id = testId
        resultBody.querySelector('.collapsible').dataset.id = id

        resultsTableRow.forEach((html) => {
            const t = document.createElement('template')
            t.innerHTML = html
            resultBody.querySelector('.collapsible').appendChild(t.content)
        })

        if (log) {
            // Wrap lines starting with "E" with span.error to color those lines red
            const wrappedLog = log.replace(/^E.*$/gm, (match) => `<span class="error">${match}</span>`)
            resultBody.querySelector('.log').innerHTML = wrappedLog
        } else {
            resultBody.querySelector('.log').remove()
        }

        if (collapsed) {
            resultBody.querySelector('.collapsible > td')?.classList.add('collapsed')
            resultBody.querySelector('.extras-row').classList.add('hidden')
        } else {
            resultBody.querySelector('.collapsible > td')?.classList.remove('collapsed')
        }

        const media = []
        extras?.forEach(({ name, format_type, content }) => {
            if (['image', 'video'].includes(format_type)) {
                media.push({ path: content, name, format_type })
            }

            if (format_type === 'html') {
                resultBody.querySelector('.extraHTML').insertAdjacentHTML('beforeend', `<div>${content}</div>`)
            }
        })
        mediaViewer.setup(resultBody, media)

        // Add custom html from the pytest_html_results_table_html hook
        tableHtml?.forEach((item) => {
            resultBody.querySelector('td[class="extra"]').insertAdjacentHTML('beforeend', item)
        })

        return resultBody
    },
}

module.exports = {
    dom,
    htmlToElements,
    find,
    findAll,
}

},{"./mediaviewer.js":6}],3:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const storageModule = require('./storage.js')

const getFilteredSubSet = (filter) =>
    manager.allData.tests.filter(({ result }) => filter.includes(result.toLowerCase()))

const doInitFilter = () => {
    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)
}

const doFilter = (type, show) => {
    if (show) {
        storageModule.showCategory(type)
    } else {
        storageModule.hideCategory(type)
    }

    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)

    const sortColumn = storageModule.getSort()
    doSort(sortColumn, true)
}

module.exports = {
    doFilter,
    doInitFilter,
}

},{"./datamanager.js":1,"./sort.js":7,"./storage.js":8}],4:[function(require,module,exports){
const { redraw, bindEvents, renderStatic } = require('./main.js')
const { doInitFilter } = require('./filter.js')
const { doInitSort } = require('./sort.js')
const { manager } = require('./datamanager.js')
const data = JSON.parse(document.getElementById('data-container').dataset.jsonblob)

function init() {
    manager.setManager(data)
    doInitFilter()
    doInitSort()
    renderStatic()
    redraw()
    bindEvents()
}

init()

},{"./datamanager.js":1,"./filter.js":3,"./main.js":5,"./sort.js":7}],5:[function(require,module,exports){
const { dom, find, findAll } = require('./dom.js')
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const { doFilter } = require('./filter.js')
const {
    getVisible,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    getSortDirection,
    possibleFilters,
} = require('./storage.js')

const removeChildren = (node) => {
    while (node.firstChild) {
        node.removeChild(node.firstChild)
    }
}

const renderStatic = () => {
    const renderEnvironmentTable = () => {
        const environment = manager.environment
        const rows = Object.keys(environment).map((key) => dom.getStaticRow(key, environment[key]))
        const table = document.getElementById('environment')
        removeChildren(table)
        rows.forEach((row) => table.appendChild(row))
    }
    renderEnvironmentTable()
}

const addItemToggleListener = (elem) => {
    elem.addEventListener('click', ({ target }) => {
        const id = target.parentElement.dataset.id
        manager.toggleCollapsedItem(id)

        const collapsedIds = getCollapsedIds()
        if (collapsedIds.includes(id)) {
            const updated = collapsedIds.filter((item) => item !== id)
            setCollapsedIds(updated)
        } else {
            collapsedIds.push(id)
            setCollapsedIds(collapsedIds)
        }
        redraw()
    })
}

const renderContent = (tests) => {
    const sortAttr = getSort(manager.initialSort)
    const sortAsc = JSON.parse(getSortDirection())
    const rows = tests.map(dom.getResultTBody)
    const table = document.getElementById('results-table')
    const tableHeader = document.getElementById('results-table-head')

    const newTable = document.createElement('table')
    newTable.id = 'results-table'

    // remove all sorting classes and set the relevant
    findAll('.sortable', tableHeader).forEach((elem) => elem.classList.remove('asc', 'desc'))
    tableHeader.querySelector(`.sortable[data-column-type="${sortAttr}"]`)?.classList.add(sortAsc ? 'desc' : 'asc')
    newTable.appendChild(tableHeader)

    if (!rows.length) {
        const emptyTable = document.getElementById('template_results-table__body--empty').content.cloneNode(true)
        newTable.appendChild(emptyTable)
    } else {
        rows.forEach((row) => {
            if (!!row) {
                findAll('.collapsible td:not(.col-links', row).forEach(addItemToggleListener)
                find('.logexpander', row).addEventListener('click',
                    (evt) => evt.target.parentNode.classList.toggle('expanded'),
                )
                newTable.appendChild(row)
            }
        })
    }

    table.replaceWith(newTable)
}

const renderDerived = () => {
    const currentFilter = getVisible()
    possibleFilters.forEach((result) => {
        const input = document.querySelector(`input[data-test-result="${result}"]`)
        input.checked = currentFilter.includes(result)
    })
}

const bindEvents = () => {
    const filterColumn = (evt) => {
        const { target: element } = evt
        const { testResult } = element.dataset

        doFilter(testResult, element.checked)
        const collapsedIds = getCollapsedIds()
        const updated = manager.renderData.tests.map((test) => {
            return {
                ...test,
                collapsed: collapsedIds.includes(test.id),
            }
        })
        manager.setRender(updated)
        redraw()
    }

    const header = document.getElementById('environment-header')
    header.addEventListener('click', () => {
        const table = document.getElementById('environment')
        table.classList.toggle('hidden')
        header.classList.toggle('collapsed')
    })

    findAll('input[name="filter_checkbox"]').forEach((elem) => {
        elem.addEventListener('click', filterColumn)
    })

    findAll('.sortable').forEach((elem) => {
        elem.addEventListener('click', (evt) => {
            const { target: element } = evt
            const { columnType } = element.dataset
            doSort(columnType)
            redraw()
        })
    })

    document.getElementById('show_all_details').addEventListener('click', () => {
        manager.allCollapsed = false
        setCollapsedIds([])
        redraw()
    })
    document.getElementById('hide_all_details').addEventListener('click', () => {
        manager.allCollapsed = true
        const allIds = manager.renderData.tests.map((test) => test.id)
        setCollapsedIds(allIds)
        redraw()
    })
}

const redraw = () => {
    const { testSubset } = manager

    renderContent(testSubset)
    renderDerived()
}

module.exports = {
    redraw,
    bindEvents,
    renderStatic,
}

},{"./datamanager.js":1,"./dom.js":2,"./filter.js":3,"./sort.js":7,"./storage.js":8}],6:[function(require,module,exports){
class MediaViewer {
    constructor(assets) {
        this.assets = assets
        this.index = 0
    }

    nextActive() {
        this.index = this.index === this.assets.length - 1 ? 0 : this.index + 1
        return [this.activeFile, this.index]
    }

    prevActive() {
        this.index = this.index === 0 ? this.assets.length - 1 : this.index -1
        return [this.activeFile, this.index]
    }

    get currentIndex() {
        return this.index
    }

    get activeFile() {
        return this.assets[this.index]
    }
}


const setup = (resultBody, assets) => {
    if (!assets.length) {
        resultBody.querySelector('.media').classList.add('hidden')
        return
    }

    const mediaViewer = new MediaViewer(assets)
    const container = resultBody.querySelector('.media-container')
    const leftArrow = resultBody.querySelector('.media-container__nav--left')
    const rightArrow = resultBody.querySelector('.media-container__nav--right')
    const mediaName = resultBody.querySelector('.media__name')
    const counter = resultBody.querySelector('.media__counter')
    const imageEl = resultBody.querySelector('img')
    const sourceEl = resultBody.querySelector('source')
    const videoEl = resultBody.querySelector('video')

    const setImg = (media, index) => {
        if (media?.format_type === 'image') {
            imageEl.src = media.path

            imageEl.classList.remove('hidden')
            videoEl.classList.add('hidden')
        } else if (media?.format_type === 'video') {
            sourceEl.src = media.path

            videoEl.classList.remove('hidden')
            imageEl.classList.add('hidden')
        }

        mediaName.innerText = media?.name
        counter.innerText = `${index + 1} / ${assets.length}`
    }
    setImg(mediaViewer.activeFile, mediaViewer.currentIndex)

    const moveLeft = () => {
        const [media, index] = mediaViewer.prevActive()
        setImg(media, index)
    }
    const doRight = () => {
        const [media, index] = mediaViewer.nextActive()
        setImg(media, index)
    }
    const openImg = () => {
        window.open(mediaViewer.activeFile.path, '_blank')
    }
    if (assets.length === 1) {
        container.classList.add('media-container--fullscreen')
    } else {
        leftArrow.addEventListener('click', moveLeft)
        rightArrow.addEventListener('click', doRight)
    }
    imageEl.addEventListener('click', openImg)
}

module.exports = {
    setup,
}

},{}],7:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const storageModule = require('./storage.js')

const genericSort = (list, key, ascending, customOrder) => {
    let sorted
    if (customOrder) {
        sorted = list.sort((a, b) => {
            const aValue = a.result.toLowerCase()
            const bValue = b.result.toLowerCase()

            const aIndex = customOrder.findIndex((item) => item.toLowerCase() === aValue)
            const bIndex = customOrder.findIndex((item) => item.toLowerCase() === bValue)

            // Compare the indices to determine the sort order
            return aIndex - bIndex
        })
    } else {
        sorted = list.sort((a, b) => a[key] === b[key] ? 0 : a[key] > b[key] ? 1 : -1)
    }

    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const durationSort = (list, ascending) => {
    const parseDuration = (duration) => {
        if (duration.includes(':')) {
            // If it's in the format "HH:mm:ss"
            const [hours, minutes, seconds] = duration.split(':').map(Number)
            return (hours * 3600 + minutes * 60 + seconds) * 1000
        } else {
            // If it's in the format "nnn ms"
            return parseInt(duration)
        }
    }
    const sorted = list.sort((a, b) => parseDuration(a['duration']) - parseDuration(b['duration']))
    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const doInitSort = () => {
    const type = storageModule.getSort(manager.initialSort)
    const ascending = storageModule.getSortDirection()
    const list = manager.testSubset
    const initialOrder = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed', 'Skipped', 'Passed']

    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    if (type?.toLowerCase() === 'original') {
        manager.setRender(list)
    } else {
        let sortedList
        switch (type) {
        case 'duration':
            sortedList = durationSort(list, ascending)
            break
        case 'result':
            sortedList = genericSort(list, type, ascending, initialOrder)
            break
        default:
            sortedList = genericSort(list, type, ascending)
            break
        }
        manager.setRender(sortedList)
    }
}

const doSort = (type, skipDirection) => {
    const newSortType = storageModule.getSort(manager.initialSort) !== type
    const currentAsc = storageModule.getSortDirection()
    let ascending
    if (skipDirection) {
        ascending = currentAsc
    } else {
        ascending = newSortType ? false : !currentAsc
    }
    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    const list = manager.testSubset
    const sortedList = type === 'duration' ? durationSort(list, ascending) : genericSort(list, type, ascending)
    manager.setRender(sortedList)
}

module.exports = {
    doInitSort,
    doSort,
}

},{"./datamanager.js":1,"./storage.js":8}],8:[function(require,module,exports){
const possibleFilters = [
    'passed',
    'skipped',
    'failed',
    'error',
    'xfailed',
    'xpassed',
    'rerun',
]

const getVisible = () => {
    const url = new URL(window.location.href)
    const settings = new URLSearchParams(url.search).get('visible')
    const lower = (item) => {
        const lowerItem = item.toLowerCase()
        if (possibleFilters.includes(lowerItem)) {
            return lowerItem
        }
        return null
    }
    return settings === null ?
        possibleFilters :
        [...new Set(settings?.split(',').map(lower).filter((item) => item))]
}

const hideCategory = (categoryToHide) => {
    const url = new URL(window.location.href)
    const visibleParams = new URLSearchParams(url.search).get('visible')
    const currentVisible = visibleParams ? visibleParams.split(',') : [...possibleFilters]
    const settings = [...new Set(currentVisible)].filter((f) => f !== categoryToHide).join(',')

    url.searchParams.set('visible', settings)
    window.history.pushState({}, null, unescape(url.href))
}

const showCategory = (categoryToShow) => {
    if (typeof window === 'undefined') {
        return
    }
    const url = new URL(window.location.href)
    const currentVisible = new URLSearchParams(url.search).get('visible')?.split(',').filter(Boolean) ||
        [...possibleFilters]
    const settings = [...new Set([categoryToShow, ...currentVisible])]
    const noFilter = possibleFilters.length === settings.length || !settings.length

    noFilter ? url.searchParams.delete('visible') : url.searchParams.set('visible', settings.join(','))
    window.history.pushState({}, null, unescape(url.href))
}

const getSort = (initialSort) => {
    const url = new URL(window.location.href)
    let sort = new URLSearchParams(url.search).get('sort')
    if (!sort) {
        sort = initialSort || 'result'
    }
    return sort
}

const setSort = (type) => {
    const url = new URL(window.location.href)
    url.searchParams.set('sort', type)
    window.history.pushState({}, null, unescape(url.href))
}

const getCollapsedCategory = (renderCollapsed) => {
    let categories
    if (typeof window !== 'undefined') {
        const url = new URL(window.location.href)
        const collapsedItems = new URLSearchParams(url.search).get('collapsed')
        switch (true) {
        case !renderCollapsed && collapsedItems === null:
            categories = ['passed']
            break
        case collapsedItems?.length === 0 || /^["']{2}$/.test(collapsedItems):
            categories = []
            break
        case /^all$/.test(collapsedItems) || collapsedItems === null && /^all$/.test(renderCollapsed):
            categories = [...possibleFilters]
            break
        default:
            categories = collapsedItems?.split(',').map((item) => item.toLowerCase()) || renderCollapsed
            break
        }
    } else {
        categories = []
    }
    return categories
}

const getSortDirection = () => JSON.parse(sessionStorage.getItem('sortAsc')) || false
const setSortDirection = (ascending) => sessionStorage.setItem('sortAsc', ascending)

const getCollapsedIds = () => JSON.parse(sessionStorage.getItem('collapsedIds')) || []
const setCollapsedIds = (list) => sessionStorage.setItem('collapsedIds', JSON.stringify(list))

module.exports = {
    getVisible,
    hideCategory,
    showCategory,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    setSort,
    getSortDirection,
    setSortDirection,
    getCollapsedCategory,
    possibleFilters,
}

},{}]},{},[4]);
    </script>
  </footer>
</html>