<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title id="head-title">chz.html</title>
      <link href="assets/style.css" rel="stylesheet" type="text/css"/>
  </head>
  <body>
    <h1 id="title">chz.html</h1>
    <p>Report generated on 06-Feb-2024 at 18:27:27 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a>
        v4.1.1</p>
    <div id="environment-header">
      <h2>Environment</h2>
    </div>
    <table id="environment"></table>
    <!-- TEMPLATES -->
      <template id="template_environment_row">
      <tr>
        <td></td>
        <td></td>
      </tr>
    </template>
    <template id="template_results-table__body--empty">
      <tbody class="results-table-row">
        <tr id="not-found-message">
          <td colspan="4">No results found. Check the filters.</th>
        </tr>
    </template>
    <template id="template_results-table__tbody">
      <tbody class="results-table-row">
        <tr class="collapsible">
        </tr>
        <tr class="extras-row">
          <td class="extra" colspan="4">
            <div class="extraHTML"></div>
            <div class="media">
              <div class="media-container">
                  <div class="media-container__nav--left"><</div>
                  <div class="media-container__viewport">
                    <img src="" />
                    <video controls>
                      <source src="" type="video/mp4">
                    </video>
                  </div>
                  <div class="media-container__nav--right">></div>
                </div>
                <div class="media__name"></div>
                <div class="media__counter"></div>
            </div>
            <div class="logwrapper">
              <div class="logexpander"></div>
              <div class="log"></div>
            </div>
          </td>
        </tr>
      </tbody>
    </template>
    <!-- END TEMPLATES -->
    <div class="summary">
      <div class="summary__data">
        <h2>Summary</h2>
        <div class="additional-summary prefix">
        </div>
        <p class="run-count">66 tests took 00:10:38.</p>
        <p class="filter">(Un)check the boxes to filter the results.</p>
        <div class="summary__reload">
          <div class="summary__reload__button hidden" onclick="location.reload()">
            <div>There are still tests running. <br />Reload this page to get the latest results!</div>
          </div>
        </div>
        <div class="summary__spacer"></div>
        <div class="controls">
          <div class="filters">
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="failed" disabled/>
            <span class="failed">0 Failed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="passed" />
            <span class="passed">66 Passed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="skipped" />
            <span class="skipped">4 Skipped,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xfailed" disabled/>
            <span class="xfailed">0 Expected failures,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xpassed" disabled/>
            <span class="xpassed">0 Unexpected passes,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="error" disabled/>
            <span class="error">0 Errors,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="rerun" disabled/>
            <span class="rerun">0 Reruns</span>
          </div>
          <div class="collapse">
            <button id="show_all_details">Show all details</button>&nbsp;/&nbsp;<button id="hide_all_details">Hide all details</button>
          </div>
        </div>
      </div>
      <div class="additional-summary summary">
      </div>
      <div class="additional-summary postfix">
      </div>
    </div>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable" data-column-type="result">Result</th>
          <th class="sortable" data-column-type="testId">Test</th>
          <th class="sortable" data-column-type="duration">Duration</th>
          <th>Links</th>
        </tr>
      </thead>
    </table>
  </body>
  <footer>
    <div id="data-container" data-jsonblob="{&#34;environment&#34;: {&#34;Python&#34;: &#34;3.9.6&#34;, &#34;Platform&#34;: &#34;macOS-14.3-arm64-arm-64bit&#34;, &#34;Packages&#34;: {&#34;pytest&#34;: &#34;7.4.2&#34;, &#34;pluggy&#34;: &#34;1.3.0&#34;}, &#34;Plugins&#34;: {&#34;html&#34;: &#34;4.1.1&#34;, &#34;mpl&#34;: &#34;0.16.1&#34;, &#34;metadata&#34;: &#34;3.0.0&#34;, &#34;json&#34;: &#34;0.4.0&#34;}}, &#34;tests&#34;: {&#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176a43d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cae6d304-8203-4415-9996-9fc3a977752e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176a4550&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cae6d304-8203-4415-9996-9fc3a977752e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176a4670&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cae6d304-8203-4415-9996-9fc3a977752e&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176a4220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ce5dd025-8a25-4b28-80c4-09ff913a48ff\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176a42e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ce5dd025-8a25-4b28-80c4-09ff913a48ff\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176a45b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ce5dd025-8a25-4b28-80c4-09ff913a48ff&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176d2460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/31119455-c09a-4524-81a5-aa42d46aca47\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176d2a30&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/31119455-c09a-4524-81a5-aa42d46aca47\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176d2850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/31119455-c09a-4524-81a5-aa42d46aca47&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176e41c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b57cd7e1-b794-45fe-a5d0-c41536d2a6a0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176e4760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b57cd7e1-b794-45fe-a5d0-c41536d2a6a0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176d2940&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b57cd7e1-b794-45fe-a5d0-c41536d2a6a0&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176a4eb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c00dcb16-7905-4f24-bb90-74950f051798\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176a4850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c00dcb16-7905-4f24-bb90-74950f051798\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176e46d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c00dcb16-7905-4f24-bb90-74950f051798&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176e4e20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/becb6c78-04c3-4b8f-a917-fd14fe75724f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f8160&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/becb6c78-04c3-4b8f-a917-fd14fe75724f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f82e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/becb6c78-04c3-4b8f-a917-fd14fe75724f&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:28&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:28&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176e4dc0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f9128d12-0360-4756-800a-5b5365fd47aa\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176e4f40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f9128d12-0360-4756-800a-5b5365fd47aa\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176e47f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f9128d12-0360-4756-800a-5b5365fd47aa&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:29&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:29&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f8b50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/aa47a3e1-4e22-42be-8980-1fca9871d7d1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f82e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/aa47a3e1-4e22-42be-8980-1fca9871d7d1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f84c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/aa47a3e1-4e22-42be-8980-1fca9871d7d1&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:98 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...cheezdev.com/&amp;#x27; == &amp;#x27;failblog.cheezdev.com/&amp;#x27;\n  - failblog.cheezdev.com/\n  + https://failblog.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f9430&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d095d5a8-5865-4f8e-9d8e-c5636fad65d2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f98b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d095d5a8-5865-4f8e-9d8e-c5636fad65d2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f81c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d095d5a8-5865-4f8e-9d8e-c5636fad65d2&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:110 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...ezburger.com/&amp;#x27; == &amp;#x27;failblog.cheezburger.com/&amp;#x27;\n  - failblog.cheezburger.com/\n  + https://failblog.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176e46d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/697eb63a-9740-4c72-91f4-bf41ee22c768\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176a4790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/697eb63a-9740-4c72-91f4-bf41ee22c768\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176a4b50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/697eb63a-9740-4c72-91f4-bf41ee22c768&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11771a040&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0d9c8836-e13a-4304-b7f5-d179678c2035\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11771a310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0d9c8836-e13a-4304-b7f5-d179678c2035\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11771a370&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0d9c8836-e13a-4304-b7f5-d179678c2035&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11771ad00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7cd9106e-d7be-4d9c-9ecb-4fb09080e03d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11771a580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7cd9106e-d7be-4d9c-9ecb-4fb09080e03d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11771a610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7cd9106e-d7be-4d9c-9ecb-4fb09080e03d&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176e4f70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5b164e87-d134-4bd6-b8fc-a353b86b75c2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f8e20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5b164e87-d134-4bd6-b8fc-a353b86b75c2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f8f10&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5b164e87-d134-4bd6-b8fc-a353b86b75c2&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117729670&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/bfb2dfb9-8976-4f0c-9617-9e4357c972fe\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177298e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/bfb2dfb9-8976-4f0c-9617-9e4357c972fe\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117729ca0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/bfb2dfb9-8976-4f0c-9617-9e4357c972fe&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;, &#34;duration&#34;: &#34;00:00:08&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:08&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11771a280&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d01816f0-2dfa-40e9-b6a3-7d652428ae3f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11771ae20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d01816f0-2dfa-40e9-b6a3-7d652428ae3f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11771a7c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d01816f0-2dfa-40e9-b6a3-7d652428ae3f&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11773a280&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5a7f55be-84c9-4b66-91b2-672a3b565f97\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11773a4f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5a7f55be-84c9-4b66-91b2-672a3b565f97\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11773a8b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5a7f55be-84c9-4b66-91b2-672a3b565f97&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11773a2b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e38366ae-0054-4f16-975e-f6a25f71a421\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11773a700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e38366ae-0054-4f16-975e-f6a25f71a421\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11773a460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e38366ae-0054-4f16-975e-f6a25f71a421&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117729be0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/319890b2-647e-4205-8e36-48fac5b209bb\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746c40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/319890b2-647e-4205-8e36-48fac5b209bb\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177463a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/319890b2-647e-4205-8e36-48fac5b209bb&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/fail_blog/test_main_desktop.py&amp;#x27;, 167, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/fail_blog/test_main_desktop.py&amp;#x27;, 181, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7b64ec8c-6dc2-42e3-8977-188837a1c63f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7b64ec8c-6dc2-42e3-8977-188837a1c63f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746280&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7b64ec8c-6dc2-42e3-8977-188837a1c63f&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11773a1f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/87baae51-4db4-4a2b-be29-9a18b9a69140\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11773a970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/87baae51-4db4-4a2b-be29-9a18b9a69140\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11773a4c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/87baae51-4db4-4a2b-be29-9a18b9a69140&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f9130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0cf9eddb-2946-4489-a428-671604c20ff6\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f96d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0cf9eddb-2946-4489-a428-671604c20ff6\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f9610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0cf9eddb-2946-4489-a428-671604c20ff6&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f9970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d13b802c-a8ed-41a6-b9a3-6e47946a458b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f9760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d13b802c-a8ed-41a6-b9a3-6e47946a458b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117729dc0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d13b802c-a8ed-41a6-b9a3-6e47946a458b&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177460d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/08277402-73f5-4d60-9706-1f943e89461e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177462e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/08277402-73f5-4d60-9706-1f943e89461e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177461c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/08277402-73f5-4d60-9706-1f943e89461e&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117757a60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/93f97d30-b199-46f5-bf83-41d630787010\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117757ac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/93f97d30-b199-46f5-bf83-41d630787010\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117757d30&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/93f97d30-b199-46f5-bf83-41d630787010&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746b20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ce0acd7-6991-49f3-9990-3ea9edea0d51\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746bb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ce0acd7-6991-49f3-9990-3ea9edea0d51\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177468e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9ce0acd7-6991-49f3-9990-3ea9edea0d51&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:29&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:29&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f9460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e6b96204-dd85-4831-9189-f9b67aee5eaa\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177670a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e6b96204-dd85-4831-9189-f9b67aee5eaa\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177674c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e6b96204-dd85-4831-9189-f9b67aee5eaa&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:98 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...cheezdev.com/&amp;#x27; == &amp;#x27;urls.icanhas_stage&amp;#x27;\n  - urls.icanhas_stage\n  + https://icanhas.cheezdev.com/\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117767c70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/71f298a3-79c8-413a-a235-ce3b723e13ae\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177761c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/71f298a3-79c8-413a-a235-ce3b723e13ae\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117776130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/71f298a3-79c8-413a-a235-ce3b723e13ae&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:110 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...ezburger.com/&amp;#x27; == &amp;#x27;icanhas.cheezburger.com/&amp;#x27;\n  - icanhas.cheezburger.com/\n  + https://icanhas.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117767250&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/65eedb51-1ccd-424d-ab2a-6cf0c0f4e7ec\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1176f9580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/65eedb51-1ccd-424d-ab2a-6cf0c0f4e7ec\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/65eedb51-1ccd-424d-ab2a-6cf0c0f4e7ec&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117776610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f0aca4b7-574c-4f18-b10f-dc2068da54d0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117776700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f0aca4b7-574c-4f18-b10f-dc2068da54d0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177761c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f0aca4b7-574c-4f18-b10f-dc2068da54d0&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177840a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0e65beca-09b2-4e55-a866-93ccfdf171fd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177842e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0e65beca-09b2-4e55-a866-93ccfdf171fd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177843a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0e65beca-09b2-4e55-a866-93ccfdf171fd&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177760d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dfd0db58-7a47-4e2a-af6e-72d3edafa991\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177466d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dfd0db58-7a47-4e2a-af6e-72d3edafa991\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746d90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dfd0db58-7a47-4e2a-af6e-72d3edafa991&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177848b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5d9502f0-4081-47e3-803d-a2b60bc16674\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177845b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5d9502f0-4081-47e3-803d-a2b60bc16674\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117784430&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5d9502f0-4081-47e3-803d-a2b60bc16674&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;, &#34;duration&#34;: &#34;00:00:08&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:08&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117793070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/88ac6f63-00a1-41f3-9141-4a008ddb55e0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177932e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/88ac6f63-00a1-41f3-9141-4a008ddb55e0\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177936a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/88ac6f63-00a1-41f3-9141-4a008ddb55e0&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117784190&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a328fde9-631e-4abd-a9fc-3097e1339de6\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117784820&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a328fde9-631e-4abd-a9fc-3097e1339de6\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746d90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/a328fde9-631e-4abd-a9fc-3097e1339de6&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177934f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fd4590f9-0dd7-47b2-8707-0cadcef5f84b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177932b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fd4590f9-0dd7-47b2-8707-0cadcef5f84b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117793bb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fd4590f9-0dd7-47b2-8707-0cadcef5f84b&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177a5a00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/81563108-1874-4d05-8894-4d986f3a874a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177a51f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/81563108-1874-4d05-8894-4d986f3a874a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177a5520&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/81563108-1874-4d05-8894-4d986f3a874a&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/icanhas/test_main_desktop.py&amp;#x27;, 167, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/icanhas/test_main_desktop.py&amp;#x27;, 181, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177460d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3d63f1b7-4487-48a2-a82b-81ea869d3d8a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117784250&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3d63f1b7-4487-48a2-a82b-81ea869d3d8a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177848e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3d63f1b7-4487-48a2-a82b-81ea869d3d8a&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/af7324c6-3bae-42de-884e-139474e17e16\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746d60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/af7324c6-3bae-42de-884e-139474e17e16\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117793190&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/af7324c6-3bae-42de-884e-139474e17e16&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177a5340&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/562c0d7c-5c81-42a1-9806-c517eff4b7d7\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177a52b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/562c0d7c-5c81-42a1-9806-c517eff4b7d7\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177a56a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/562c0d7c-5c81-42a1-9806-c517eff4b7d7&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177b0b80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cbbe8e99-3a3f-43ae-8d30-e7a1644e017e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177b0d90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cbbe8e99-3a3f-43ae-8d30-e7a1644e017e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177b0e80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cbbe8e99-3a3f-43ae-8d30-e7a1644e017e&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177b0f70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3b94fcac-36a5-45d2-8d94-34e78241fdb1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177a5430&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3b94fcac-36a5-45d2-8d94-34e78241fdb1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177a5400&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3b94fcac-36a5-45d2-8d94-34e78241fdb1&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117746a60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fd813d28-9a6d-4b7f-b085-256970b157f1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117784250&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fd813d28-9a6d-4b7f-b085-256970b157f1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117784580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fd813d28-9a6d-4b7f-b085-256970b157f1&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:34&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:34&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177bfc40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/effd87f2-c87d-4e3f-b08c-d194a9e7d9c1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177cc040&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/effd87f2-c87d-4e3f-b08c-d194a9e7d9c1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177cc1c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/effd87f2-c87d-4e3f-b08c-d194a9e7d9c1&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:35&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:35&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177b0790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ff8c295c-9f32-48b6-861e-1f0019a1ae29\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177b0b80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ff8c295c-9f32-48b6-861e-1f0019a1ae29\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177b0c40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ff8c295c-9f32-48b6-861e-1f0019a1ae29&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:97 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...cheezdev.com/&amp;#x27; == &amp;#x27;failblog.cheezdev.com/&amp;#x27;\n  - failblog.cheezdev.com/\n  + https://failblog.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177cc820&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5596407b-3b41-4de6-966c-ba5aa021af37\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ccca0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5596407b-3b41-4de6-966c-ba5aa021af37\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177cca60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5596407b-3b41-4de6-966c-ba5aa021af37&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:109 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...ezburger.com/&amp;#x27; == &amp;#x27;failblog.cheezburger.com/&amp;#x27;\n  - failblog.cheezburger.com/\n  + https://failblog.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ccb20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/80600e18-696f-4c3f-bc07-56124345d6ba\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177cc5b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/80600e18-696f-4c3f-bc07-56124345d6ba\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177cc970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/80600e18-696f-4c3f-bc07-56124345d6ba&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:121 Assertion failed: Unexpected URL after scrolling up on the page\nassert &amp;#x27;https://fail...cheezdev.com/&amp;#x27; == &amp;#x27;failblog.cheezdev.com/&amp;#x27;\n  - failblog.cheezdev.com/\n  + https://failblog.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177db9a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/268817af-8961-4872-a894-1a1f21ca4845\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177db940&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/268817af-8961-4872-a894-1a1f21ca4845\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177dba30&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/268817af-8961-4872-a894-1a1f21ca4845&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:133 Assertion failed: Unexpected URL after scrolling up on the page\nassert &amp;#x27;https://fail...ezburger.com/&amp;#x27; == &amp;#x27;failblog.cheezburger.com/&amp;#x27;\n  - failblog.cheezburger.com/\n  + https://failblog.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/65253f56-e882-4553-83fb-c5e902ecd0a9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec5b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/65253f56-e882-4553-83fb-c5e902ecd0a9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec370&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/65253f56-e882-4553-83fb-c5e902ecd0a9&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ccfa0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0c76b809-e5c6-4ef6-9f1b-061649bbd993\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ccac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0c76b809-e5c6-4ef6-9f1b-061649bbd993\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ccfd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0c76b809-e5c6-4ef6-9f1b-061649bbd993&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec820&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6b02b0d3-49a3-4902-96f0-2d41af25e88d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6b02b0d3-49a3-4902-96f0-2d41af25e88d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177fb100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6b02b0d3-49a3-4902-96f0-2d41af25e88d&#34;}], &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;----------------------------- Captured stdout call -----------------------------\nError during execution: Message: Unable to locate element: body.mu-ichc.mu-Channel.language-english.mu-theme-light; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\ndom.find/&amp;lt;/&amp;lt;@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ecb80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9bca1e11-f8df-4799-a034-4c27ef052255\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec160&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9bca1e11-f8df-4799-a034-4c27ef052255\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9bca1e11-f8df-4799-a034-4c27ef052255&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177cca30&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c1879871-64c6-412b-bfcc-5fa3c481cc4e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ccb80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c1879871-64c6-412b-bfcc-5fa3c481cc4e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ccac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c1879871-64c6-412b-bfcc-5fa3c481cc4e&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177fb8e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fdd0f4c3-2b32-446d-8efd-de858dfb392b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177fbe20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fdd0f4c3-2b32-446d-8efd-de858dfb392b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177fb340&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fdd0f4c3-2b32-446d-8efd-de858dfb392b&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177fb1c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d4a26351-2276-4a66-a0f1-a12f846fb728\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177fba00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d4a26351-2276-4a66-a0f1-a12f846fb728\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177cc820&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d4a26351-2276-4a66-a0f1-a12f846fb728&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec370&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/55a30923-6335-4b72-b520-16cada101090\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177eca30&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/55a30923-6335-4b72-b520-16cada101090\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec2e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/55a30923-6335-4b72-b520-16cada101090&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177f0970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f22a56d0-41d7-4219-a053-05a50aeb8a72\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177f0e20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f22a56d0-41d7-4219-a053-05a50aeb8a72\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177f0bb0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f22a56d0-41d7-4219-a053-05a50aeb8a72&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ecf70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/54837c63-c2c9-4db7-93fb-830913bff05d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/54837c63-c2c9-4db7-93fb-830913bff05d\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/54837c63-c2c9-4db7-93fb-830913bff05d&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177fb5e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ca6312c0-d008-45ca-b5dc-c3af48bf5b35\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117819460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ca6312c0-d008-45ca-b5dc-c3af48bf5b35\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117819310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ca6312c0-d008-45ca-b5dc-c3af48bf5b35&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:35&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:35&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:326 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117819b50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f4757f04-d648-4956-9b16-5af0157184bd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1178198e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f4757f04-d648-4956-9b16-5af0157184bd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11782a0a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f4757f04-d648-4956-9b16-5af0157184bd&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:97 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...cheezdev.com/&amp;#x27; == &amp;#x27;icanhas.cheezdev.com/&amp;#x27;\n  - icanhas.cheezdev.com/\n  + https://icanhas.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177eca30&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ccbec09d-5f5d-4e7e-8f2c-d61c66f1660e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec520&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ccbec09d-5f5d-4e7e-8f2c-d61c66f1660e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ec2b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ccbec09d-5f5d-4e7e-8f2c-d61c66f1660e&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:109 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...ezburger.com/&amp;#x27; == &amp;#x27;icanhas.cheezburger.com/&amp;#x27;\n  - icanhas.cheezburger.com/\n  + https://icanhas.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11782a790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b5c7d1d7-b6dc-4e5e-bf78-a8ff94b3563a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11782ac10&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b5c7d1d7-b6dc-4e5e-bf78-a8ff94b3563a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11782a9d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b5c7d1d7-b6dc-4e5e-bf78-a8ff94b3563a&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:123 Assertion failed: URL inesperada despu\u00e9s de desplazarse hacia arriba en la p\u00e1gina \nassert &amp;#x27;https://ican...cheezdev.com/&amp;#x27; == &amp;#x27;icanhas.cheezdev.com/&amp;#x27;\n  - icanhas.cheezdev.com/\n  + https://icanhas.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11782ad90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cb36ff59-9827-4ed5-b6a9-761c4619b7e3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11782a9a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cb36ff59-9827-4ed5-b6a9-761c4619b7e3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11782ab80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/cb36ff59-9827-4ed5-b6a9-761c4619b7e3&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:137 Assertion failed: URL inesperada despu\u00e9s de desplazarse hacia arriba en la p\u00e1gina \nassert &amp;#x27;https://ican...ezburger.com/&amp;#x27; == &amp;#x27;icanhas.cheezburger.com/&amp;#x27;\n  - icanhas.cheezburger.com/\n  + https://icanhas.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117835910&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/08fabd27-ead3-4dae-8d33-3157a736ea80\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117835850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/08fabd27-ead3-4dae-8d33-3157a736ea80\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1178351c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/08fabd27-ead3-4dae-8d33-3157a736ea80&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117835970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/628bd472-54e3-4ae7-9d69-38de961be137\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117835880&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/628bd472-54e3-4ae7-9d69-38de961be137\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1177ece80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/628bd472-54e3-4ae7-9d69-38de961be137&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11784a130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/79152b9f-7896-4055-9595-937abaf07ec9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11784a2e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/79152b9f-7896-4055-9595-937abaf07ec9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11784a460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/79152b9f-7896-4055-9595-937abaf07ec9&#34;}], &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;----------------------------- Captured stdout call -----------------------------\nError during execution: Message: Element &amp;lt;button class=&amp;quot;mu-btn mu-theme-btn mu-script&amp;quot;&amp;gt; is not clickable at point (432,21) because another element &amp;lt;div class=&amp;quot;pushly_popover-message-headline pushly-prompt-message-headline&amp;quot;&amp;gt; obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:335:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:176:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:135:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:204:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:84:31\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11784ac40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b31fb0ad-c216-4221-8ae2-85b85cef32dd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x117853040&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b31fb0ad-c216-4221-8ae2-85b85cef32dd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1178531c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b31fb0ad-c216-4221-8ae2-85b85cef32dd&#34;}]}, &#34;renderCollapsed&#34;: [&#34;passed&#34;], &#34;initialSort&#34;: &#34;result&#34;, &#34;title&#34;: &#34;chz.html&#34;}"></div>
    <script>
      (function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
const { getCollapsedCategory, setCollapsedIds } = require('./storage.js')

class DataManager {
    setManager(data) {
        const collapsedCategories = [...getCollapsedCategory(data.renderCollapsed)]
        const collapsedIds = []
        const tests = Object.values(data.tests).flat().map((test, index) => {
            const collapsed = collapsedCategories.includes(test.result.toLowerCase())
            const id = `test_${index}`
            if (collapsed) {
                collapsedIds.push(id)
            }
            return {
                ...test,
                id,
                collapsed,
            }
        })
        const dataBlob = { ...data, tests }
        this.data = { ...dataBlob }
        this.renderData = { ...dataBlob }
        setCollapsedIds(collapsedIds)
    }

    get allData() {
        return { ...this.data }
    }

    resetRender() {
        this.renderData = { ...this.data }
    }

    setRender(data) {
        this.renderData.tests = [...data]
    }

    toggleCollapsedItem(id) {
        this.renderData.tests = this.renderData.tests.map((test) =>
            test.id === id ? { ...test, collapsed: !test.collapsed } : test,
        )
    }

    set allCollapsed(collapsed) {
        this.renderData = { ...this.renderData, tests: [...this.renderData.tests.map((test) => (
            { ...test, collapsed }
        ))] }
    }

    get testSubset() {
        return [...this.renderData.tests]
    }

    get environment() {
        return this.renderData.environment
    }

    get initialSort() {
        return this.data.initialSort
    }
}

module.exports = {
    manager: new DataManager(),
}

},{"./storage.js":8}],2:[function(require,module,exports){
const mediaViewer = require('./mediaviewer.js')
const templateEnvRow = document.getElementById('template_environment_row')
const templateResult = document.getElementById('template_results-table__tbody')

function htmlToElements(html) {
    const temp = document.createElement('template')
    temp.innerHTML = html
    return temp.content.childNodes
}

const find = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return elem.querySelector(selector)
}

const findAll = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return [...elem.querySelectorAll(selector)]
}

const dom = {
    getStaticRow: (key, value) => {
        const envRow = templateEnvRow.content.cloneNode(true)
        const isObj = typeof value === 'object' && value !== null
        const values = isObj ? Object.keys(value).map((k) => `${k}: ${value[k]}`) : null

        const valuesElement = htmlToElements(
            values ? `<ul>${values.map((val) => `<li>${val}</li>`).join('')}<ul>` : `<div>${value}</div>`)[0]
        const td = findAll('td', envRow)
        td[0].textContent = key
        td[1].appendChild(valuesElement)

        return envRow
    },
    getResultTBody: ({ testId, id, log, extras, resultsTableRow, tableHtml, result, collapsed }) => {
        const resultBody = templateResult.content.cloneNode(true)
        resultBody.querySelector('tbody').classList.add(result.toLowerCase())
        resultBody.querySelector('tbody').id = testId
        resultBody.querySelector('.collapsible').dataset.id = id

        resultsTableRow.forEach((html) => {
            const t = document.createElement('template')
            t.innerHTML = html
            resultBody.querySelector('.collapsible').appendChild(t.content)
        })

        if (log) {
            // Wrap lines starting with "E" with span.error to color those lines red
            const wrappedLog = log.replace(/^E.*$/gm, (match) => `<span class="error">${match}</span>`)
            resultBody.querySelector('.log').innerHTML = wrappedLog
        } else {
            resultBody.querySelector('.log').remove()
        }

        if (collapsed) {
            resultBody.querySelector('.collapsible > td')?.classList.add('collapsed')
            resultBody.querySelector('.extras-row').classList.add('hidden')
        } else {
            resultBody.querySelector('.collapsible > td')?.classList.remove('collapsed')
        }

        const media = []
        extras?.forEach(({ name, format_type, content }) => {
            if (['image', 'video'].includes(format_type)) {
                media.push({ path: content, name, format_type })
            }

            if (format_type === 'html') {
                resultBody.querySelector('.extraHTML').insertAdjacentHTML('beforeend', `<div>${content}</div>`)
            }
        })
        mediaViewer.setup(resultBody, media)

        // Add custom html from the pytest_html_results_table_html hook
        tableHtml?.forEach((item) => {
            resultBody.querySelector('td[class="extra"]').insertAdjacentHTML('beforeend', item)
        })

        return resultBody
    },
}

module.exports = {
    dom,
    htmlToElements,
    find,
    findAll,
}

},{"./mediaviewer.js":6}],3:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const storageModule = require('./storage.js')

const getFilteredSubSet = (filter) =>
    manager.allData.tests.filter(({ result }) => filter.includes(result.toLowerCase()))

const doInitFilter = () => {
    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)
}

const doFilter = (type, show) => {
    if (show) {
        storageModule.showCategory(type)
    } else {
        storageModule.hideCategory(type)
    }

    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)

    const sortColumn = storageModule.getSort()
    doSort(sortColumn, true)
}

module.exports = {
    doFilter,
    doInitFilter,
}

},{"./datamanager.js":1,"./sort.js":7,"./storage.js":8}],4:[function(require,module,exports){
const { redraw, bindEvents, renderStatic } = require('./main.js')
const { doInitFilter } = require('./filter.js')
const { doInitSort } = require('./sort.js')
const { manager } = require('./datamanager.js')
const data = JSON.parse(document.getElementById('data-container').dataset.jsonblob)

function init() {
    manager.setManager(data)
    doInitFilter()
    doInitSort()
    renderStatic()
    redraw()
    bindEvents()
}

init()

},{"./datamanager.js":1,"./filter.js":3,"./main.js":5,"./sort.js":7}],5:[function(require,module,exports){
const { dom, find, findAll } = require('./dom.js')
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const { doFilter } = require('./filter.js')
const {
    getVisible,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    getSortDirection,
    possibleFilters,
} = require('./storage.js')

const removeChildren = (node) => {
    while (node.firstChild) {
        node.removeChild(node.firstChild)
    }
}

const renderStatic = () => {
    const renderEnvironmentTable = () => {
        const environment = manager.environment
        const rows = Object.keys(environment).map((key) => dom.getStaticRow(key, environment[key]))
        const table = document.getElementById('environment')
        removeChildren(table)
        rows.forEach((row) => table.appendChild(row))
    }
    renderEnvironmentTable()
}

const addItemToggleListener = (elem) => {
    elem.addEventListener('click', ({ target }) => {
        const id = target.parentElement.dataset.id
        manager.toggleCollapsedItem(id)

        const collapsedIds = getCollapsedIds()
        if (collapsedIds.includes(id)) {
            const updated = collapsedIds.filter((item) => item !== id)
            setCollapsedIds(updated)
        } else {
            collapsedIds.push(id)
            setCollapsedIds(collapsedIds)
        }
        redraw()
    })
}

const renderContent = (tests) => {
    const sortAttr = getSort(manager.initialSort)
    const sortAsc = JSON.parse(getSortDirection())
    const rows = tests.map(dom.getResultTBody)
    const table = document.getElementById('results-table')
    const tableHeader = document.getElementById('results-table-head')

    const newTable = document.createElement('table')
    newTable.id = 'results-table'

    // remove all sorting classes and set the relevant
    findAll('.sortable', tableHeader).forEach((elem) => elem.classList.remove('asc', 'desc'))
    tableHeader.querySelector(`.sortable[data-column-type="${sortAttr}"]`)?.classList.add(sortAsc ? 'desc' : 'asc')
    newTable.appendChild(tableHeader)

    if (!rows.length) {
        const emptyTable = document.getElementById('template_results-table__body--empty').content.cloneNode(true)
        newTable.appendChild(emptyTable)
    } else {
        rows.forEach((row) => {
            if (!!row) {
                findAll('.collapsible td:not(.col-links', row).forEach(addItemToggleListener)
                find('.logexpander', row).addEventListener('click',
                    (evt) => evt.target.parentNode.classList.toggle('expanded'),
                )
                newTable.appendChild(row)
            }
        })
    }

    table.replaceWith(newTable)
}

const renderDerived = () => {
    const currentFilter = getVisible()
    possibleFilters.forEach((result) => {
        const input = document.querySelector(`input[data-test-result="${result}"]`)
        input.checked = currentFilter.includes(result)
    })
}

const bindEvents = () => {
    const filterColumn = (evt) => {
        const { target: element } = evt
        const { testResult } = element.dataset

        doFilter(testResult, element.checked)
        const collapsedIds = getCollapsedIds()
        const updated = manager.renderData.tests.map((test) => {
            return {
                ...test,
                collapsed: collapsedIds.includes(test.id),
            }
        })
        manager.setRender(updated)
        redraw()
    }

    const header = document.getElementById('environment-header')
    header.addEventListener('click', () => {
        const table = document.getElementById('environment')
        table.classList.toggle('hidden')
        header.classList.toggle('collapsed')
    })

    findAll('input[name="filter_checkbox"]').forEach((elem) => {
        elem.addEventListener('click', filterColumn)
    })

    findAll('.sortable').forEach((elem) => {
        elem.addEventListener('click', (evt) => {
            const { target: element } = evt
            const { columnType } = element.dataset
            doSort(columnType)
            redraw()
        })
    })

    document.getElementById('show_all_details').addEventListener('click', () => {
        manager.allCollapsed = false
        setCollapsedIds([])
        redraw()
    })
    document.getElementById('hide_all_details').addEventListener('click', () => {
        manager.allCollapsed = true
        const allIds = manager.renderData.tests.map((test) => test.id)
        setCollapsedIds(allIds)
        redraw()
    })
}

const redraw = () => {
    const { testSubset } = manager

    renderContent(testSubset)
    renderDerived()
}

module.exports = {
    redraw,
    bindEvents,
    renderStatic,
}

},{"./datamanager.js":1,"./dom.js":2,"./filter.js":3,"./sort.js":7,"./storage.js":8}],6:[function(require,module,exports){
class MediaViewer {
    constructor(assets) {
        this.assets = assets
        this.index = 0
    }

    nextActive() {
        this.index = this.index === this.assets.length - 1 ? 0 : this.index + 1
        return [this.activeFile, this.index]
    }

    prevActive() {
        this.index = this.index === 0 ? this.assets.length - 1 : this.index -1
        return [this.activeFile, this.index]
    }

    get currentIndex() {
        return this.index
    }

    get activeFile() {
        return this.assets[this.index]
    }
}


const setup = (resultBody, assets) => {
    if (!assets.length) {
        resultBody.querySelector('.media').classList.add('hidden')
        return
    }

    const mediaViewer = new MediaViewer(assets)
    const container = resultBody.querySelector('.media-container')
    const leftArrow = resultBody.querySelector('.media-container__nav--left')
    const rightArrow = resultBody.querySelector('.media-container__nav--right')
    const mediaName = resultBody.querySelector('.media__name')
    const counter = resultBody.querySelector('.media__counter')
    const imageEl = resultBody.querySelector('img')
    const sourceEl = resultBody.querySelector('source')
    const videoEl = resultBody.querySelector('video')

    const setImg = (media, index) => {
        if (media?.format_type === 'image') {
            imageEl.src = media.path

            imageEl.classList.remove('hidden')
            videoEl.classList.add('hidden')
        } else if (media?.format_type === 'video') {
            sourceEl.src = media.path

            videoEl.classList.remove('hidden')
            imageEl.classList.add('hidden')
        }

        mediaName.innerText = media?.name
        counter.innerText = `${index + 1} / ${assets.length}`
    }
    setImg(mediaViewer.activeFile, mediaViewer.currentIndex)

    const moveLeft = () => {
        const [media, index] = mediaViewer.prevActive()
        setImg(media, index)
    }
    const doRight = () => {
        const [media, index] = mediaViewer.nextActive()
        setImg(media, index)
    }
    const openImg = () => {
        window.open(mediaViewer.activeFile.path, '_blank')
    }
    if (assets.length === 1) {
        container.classList.add('media-container--fullscreen')
    } else {
        leftArrow.addEventListener('click', moveLeft)
        rightArrow.addEventListener('click', doRight)
    }
    imageEl.addEventListener('click', openImg)
}

module.exports = {
    setup,
}

},{}],7:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const storageModule = require('./storage.js')

const genericSort = (list, key, ascending, customOrder) => {
    let sorted
    if (customOrder) {
        sorted = list.sort((a, b) => {
            const aValue = a.result.toLowerCase()
            const bValue = b.result.toLowerCase()

            const aIndex = customOrder.findIndex((item) => item.toLowerCase() === aValue)
            const bIndex = customOrder.findIndex((item) => item.toLowerCase() === bValue)

            // Compare the indices to determine the sort order
            return aIndex - bIndex
        })
    } else {
        sorted = list.sort((a, b) => a[key] === b[key] ? 0 : a[key] > b[key] ? 1 : -1)
    }

    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const durationSort = (list, ascending) => {
    const parseDuration = (duration) => {
        if (duration.includes(':')) {
            // If it's in the format "HH:mm:ss"
            const [hours, minutes, seconds] = duration.split(':').map(Number)
            return (hours * 3600 + minutes * 60 + seconds) * 1000
        } else {
            // If it's in the format "nnn ms"
            return parseInt(duration)
        }
    }
    const sorted = list.sort((a, b) => parseDuration(a['duration']) - parseDuration(b['duration']))
    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const doInitSort = () => {
    const type = storageModule.getSort(manager.initialSort)
    const ascending = storageModule.getSortDirection()
    const list = manager.testSubset
    const initialOrder = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed', 'Skipped', 'Passed']

    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    if (type?.toLowerCase() === 'original') {
        manager.setRender(list)
    } else {
        let sortedList
        switch (type) {
        case 'duration':
            sortedList = durationSort(list, ascending)
            break
        case 'result':
            sortedList = genericSort(list, type, ascending, initialOrder)
            break
        default:
            sortedList = genericSort(list, type, ascending)
            break
        }
        manager.setRender(sortedList)
    }
}

const doSort = (type, skipDirection) => {
    const newSortType = storageModule.getSort(manager.initialSort) !== type
    const currentAsc = storageModule.getSortDirection()
    let ascending
    if (skipDirection) {
        ascending = currentAsc
    } else {
        ascending = newSortType ? false : !currentAsc
    }
    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    const list = manager.testSubset
    const sortedList = type === 'duration' ? durationSort(list, ascending) : genericSort(list, type, ascending)
    manager.setRender(sortedList)
}

module.exports = {
    doInitSort,
    doSort,
}

},{"./datamanager.js":1,"./storage.js":8}],8:[function(require,module,exports){
const possibleFilters = [
    'passed',
    'skipped',
    'failed',
    'error',
    'xfailed',
    'xpassed',
    'rerun',
]

const getVisible = () => {
    const url = new URL(window.location.href)
    const settings = new URLSearchParams(url.search).get('visible')
    const lower = (item) => {
        const lowerItem = item.toLowerCase()
        if (possibleFilters.includes(lowerItem)) {
            return lowerItem
        }
        return null
    }
    return settings === null ?
        possibleFilters :
        [...new Set(settings?.split(',').map(lower).filter((item) => item))]
}

const hideCategory = (categoryToHide) => {
    const url = new URL(window.location.href)
    const visibleParams = new URLSearchParams(url.search).get('visible')
    const currentVisible = visibleParams ? visibleParams.split(',') : [...possibleFilters]
    const settings = [...new Set(currentVisible)].filter((f) => f !== categoryToHide).join(',')

    url.searchParams.set('visible', settings)
    window.history.pushState({}, null, unescape(url.href))
}

const showCategory = (categoryToShow) => {
    if (typeof window === 'undefined') {
        return
    }
    const url = new URL(window.location.href)
    const currentVisible = new URLSearchParams(url.search).get('visible')?.split(',').filter(Boolean) ||
        [...possibleFilters]
    const settings = [...new Set([categoryToShow, ...currentVisible])]
    const noFilter = possibleFilters.length === settings.length || !settings.length

    noFilter ? url.searchParams.delete('visible') : url.searchParams.set('visible', settings.join(','))
    window.history.pushState({}, null, unescape(url.href))
}

const getSort = (initialSort) => {
    const url = new URL(window.location.href)
    let sort = new URLSearchParams(url.search).get('sort')
    if (!sort) {
        sort = initialSort || 'result'
    }
    return sort
}

const setSort = (type) => {
    const url = new URL(window.location.href)
    url.searchParams.set('sort', type)
    window.history.pushState({}, null, unescape(url.href))
}

const getCollapsedCategory = (renderCollapsed) => {
    let categories
    if (typeof window !== 'undefined') {
        const url = new URL(window.location.href)
        const collapsedItems = new URLSearchParams(url.search).get('collapsed')
        switch (true) {
        case !renderCollapsed && collapsedItems === null:
            categories = ['passed']
            break
        case collapsedItems?.length === 0 || /^["']{2}$/.test(collapsedItems):
            categories = []
            break
        case /^all$/.test(collapsedItems) || collapsedItems === null && /^all$/.test(renderCollapsed):
            categories = [...possibleFilters]
            break
        default:
            categories = collapsedItems?.split(',').map((item) => item.toLowerCase()) || renderCollapsed
            break
        }
    } else {
        categories = []
    }
    return categories
}

const getSortDirection = () => JSON.parse(sessionStorage.getItem('sortAsc')) || false
const setSortDirection = (ascending) => sessionStorage.setItem('sortAsc', ascending)

const getCollapsedIds = () => JSON.parse(sessionStorage.getItem('collapsedIds')) || []
const setCollapsedIds = (list) => sessionStorage.setItem('collapsedIds', JSON.stringify(list))

module.exports = {
    getVisible,
    hideCategory,
    showCategory,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    setSort,
    getSortDirection,
    setSortDirection,
    getCollapsedCategory,
    possibleFilters,
}

},{}]},{},[4]);
    </script>
  </footer>
</html>