<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title id="head-title">chz.html</title>
      <link href="assets/style.css" rel="stylesheet" type="text/css"/>
  </head>
  <body>
    <h1 id="title">chz.html</h1>
    <p>Report generated on 24-Feb-2024 at 17:52:46 by <a href="https://pypi.python.org/pypi/pytest-html">pytest-html</a>
        v4.1.1</p>
    <div id="environment-header">
      <h2>Environment</h2>
    </div>
    <table id="environment"></table>
    <!-- TEMPLATES -->
      <template id="template_environment_row">
      <tr>
        <td></td>
        <td></td>
      </tr>
    </template>
    <template id="template_results-table__body--empty">
      <tbody class="results-table-row">
        <tr id="not-found-message">
          <td colspan="4">No results found. Check the filters.</th>
        </tr>
    </template>
    <template id="template_results-table__tbody">
      <tbody class="results-table-row">
        <tr class="collapsible">
        </tr>
        <tr class="extras-row">
          <td class="extra" colspan="4">
            <div class="extraHTML"></div>
            <div class="media">
              <div class="media-container">
                  <div class="media-container__nav--left"><</div>
                  <div class="media-container__viewport">
                    <img src="" />
                    <video controls>
                      <source src="" type="video/mp4">
                    </video>
                  </div>
                  <div class="media-container__nav--right">></div>
                </div>
                <div class="media__name"></div>
                <div class="media__counter"></div>
            </div>
            <div class="logwrapper">
              <div class="logexpander"></div>
              <div class="log"></div>
            </div>
          </td>
        </tr>
      </tbody>
    </template>
    <!-- END TEMPLATES -->
    <div class="summary">
      <div class="summary__data">
        <h2>Summary</h2>
        <div class="additional-summary prefix">
        </div>
        <p class="run-count">66 tests took 00:10:16.</p>
        <p class="filter">(Un)check the boxes to filter the results.</p>
        <div class="summary__reload">
          <div class="summary__reload__button hidden" onclick="location.reload()">
            <div>There are still tests running. <br />Reload this page to get the latest results!</div>
          </div>
        </div>
        <div class="summary__spacer"></div>
        <div class="controls">
          <div class="filters">
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="failed" disabled/>
            <span class="failed">0 Failed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="passed" />
            <span class="passed">66 Passed,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="skipped" />
            <span class="skipped">4 Skipped,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xfailed" disabled/>
            <span class="xfailed">0 Expected failures,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="xpassed" disabled/>
            <span class="xpassed">0 Unexpected passes,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="error" disabled/>
            <span class="error">0 Errors,</span>
            <input checked="true" class="filter" name="filter_checkbox" type="checkbox" data-test-result="rerun" disabled/>
            <span class="rerun">0 Reruns</span>
          </div>
          <div class="collapse">
            <button id="show_all_details">Show all details</button>&nbsp;/&nbsp;<button id="hide_all_details">Hide all details</button>
          </div>
        </div>
      </div>
      <div class="additional-summary summary">
      </div>
      <div class="additional-summary postfix">
      </div>
    </div>
    <table id="results-table">
      <thead id="results-table-head">
        <tr>
          <th class="sortable" data-column-type="result">Result</th>
          <th class="sortable" data-column-type="testId">Test</th>
          <th class="sortable" data-column-type="duration">Duration</th>
          <th>Links</th>
        </tr>
      </thead>
    </table>
  </body>
  <footer>
    <div id="data-container" data-jsonblob="{&#34;environment&#34;: {&#34;Python&#34;: &#34;3.9.6&#34;, &#34;Platform&#34;: &#34;macOS-14.3.1-arm64-arm-64bit&#34;, &#34;Packages&#34;: {&#34;pytest&#34;: &#34;7.4.2&#34;, &#34;pluggy&#34;: &#34;1.3.0&#34;}, &#34;Plugins&#34;: {&#34;html&#34;: &#34;4.1.1&#34;, &#34;mpl&#34;: &#34;0.16.1&#34;, &#34;metadata&#34;: &#34;3.0.0&#34;, &#34;json&#34;: &#34;0.4.0&#34;}}, &#34;tests&#34;: {&#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:09&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:09&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1080e4400&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1c11bf34-b43b-4d40-b2de-449f71923daa\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1080e4760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1c11bf34-b43b-4d40-b2de-449f71923daa\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1080e4880&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/1c11bf34-b43b-4d40-b2de-449f71923daa&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1080e44c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/900b2405-f788-4196-b21c-c26d888fb1d4\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1080e4490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/900b2405-f788-4196-b21c-c26d888fb1d4\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1080e4640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/900b2405-f788-4196-b21c-c26d888fb1d4&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197ae700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f8d5d081-bf45-49f4-9390-0f16b4e4970f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197aecd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f8d5d081-bf45-49f4-9390-0f16b4e4970f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197aeaf0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f8d5d081-bf45-49f4-9390-0f16b4e4970f&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197bd460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7b009373-96ed-4f57-80b0-df8e7ac5f407\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197bda00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7b009373-96ed-4f57-80b0-df8e7ac5f407\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197aebe0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7b009373-96ed-4f57-80b0-df8e7ac5f407&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1080e4760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7dbdd7bd-1ec8-4773-be2a-f47c533839a3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1080e4a60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7dbdd7bd-1ec8-4773-be2a-f47c533839a3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197bd970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7dbdd7bd-1ec8-4773-be2a-f47c533839a3&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197ce250&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9a1ff650-9d6d-4c60-8e81-d5bad26ecdb6\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197ce400&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9a1ff650-9d6d-4c60-8e81-d5bad26ecdb6\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197ce580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/9a1ff650-9d6d-4c60-8e81-d5bad26ecdb6&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:27&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:27&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:327 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197ced60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/021a3a1e-0559-421d-93e8-091848c191e9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197ce700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/021a3a1e-0559-421d-93e8-091848c191e9\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197ce5b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/021a3a1e-0559-421d-93e8-091848c191e9&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:28&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:28&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:327 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197bd160&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fcc6c34e-0da0-47e8-8732-e895583bbe3a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197aea60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fcc6c34e-0da0-47e8-8732-e895583bbe3a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197ae400&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fcc6c34e-0da0-47e8-8732-e895583bbe3a&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:98 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...cheezdev.com/&amp;#x27; == &amp;#x27;failblog.cheezdev.com/&amp;#x27;\n  - failblog.cheezdev.com/\n  + https://failblog.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197e06d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/71263e3c-b807-4c0f-a72a-47fc2d1b1805\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197e0b50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/71263e3c-b807-4c0f-a72a-47fc2d1b1805\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197aed60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/71263e3c-b807-4c0f-a72a-47fc2d1b1805&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:110 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...ezburger.com/&amp;#x27; == &amp;#x27;failblog.cheezburger.com/&amp;#x27;\n  - failblog.cheezburger.com/\n  + https://failblog.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197ce580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/02bc40b4-8334-4973-90e2-07648d772e71\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197cee20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/02bc40b4-8334-4973-90e2-07648d772e71\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197e0be0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/02bc40b4-8334-4973-90e2-07648d772e71&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;, &#34;duration&#34;: &#34;00:00:11&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:11&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f22b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e162a124-88c2-4ed3-aae4-de3252b83204\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f25b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e162a124-88c2-4ed3-aae4-de3252b83204\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f2610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e162a124-88c2-4ed3-aae4-de3252b83204&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f2a00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/47c49216-1a33-427b-82e2-cceaf8fb7953\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f28b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/47c49216-1a33-427b-82e2-cceaf8fb7953\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f22e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/47c49216-1a33-427b-82e2-cceaf8fb7953&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197aedf0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/308c12fd-d5c7-4019-93e0-c08f6519f751\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197ae6d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/308c12fd-d5c7-4019-93e0-c08f6519f751\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119801190&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/308c12fd-d5c7-4019-93e0-c08f6519f751&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_facebook_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119801910&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4f50653f-918c-4637-a3e8-6ce8e5d72294\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119801b80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4f50653f-918c-4637-a3e8-6ce8e5d72294\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119801e50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4f50653f-918c-4637-a3e8-6ce8e5d72294&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_twitter_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f28e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fdfd7cb6-94be-4be3-b9dd-71fe39bfeb24\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f2700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fdfd7cb6-94be-4be3-b9dd-71fe39bfeb24\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f22b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/fdfd7cb6-94be-4be3-b9dd-71fe39bfeb24&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119810520&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2f455fee-47f1-4cc2-9fcc-3b5bac12dea1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119810790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2f455fee-47f1-4cc2-9fcc-3b5bac12dea1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119810b50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2f455fee-47f1-4cc2-9fcc-3b5bac12dea1&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f2310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4d4c8672-ade7-419e-a7ac-b01520ea436b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f25e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4d4c8672-ade7-419e-a7ac-b01520ea436b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f23d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4d4c8672-ade7-419e-a7ac-b01520ea436b&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981ddf0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/672ae368-b14d-4bb8-bb8c-bc0b86a9aed1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981de80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/672ae368-b14d-4bb8-bb8c-bc0b86a9aed1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981dfd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/672ae368-b14d-4bb8-bb8c-bc0b86a9aed1&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_submit::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/fail_blog/test_main_desktop.py&amp;#x27;, 167, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/fail_blog/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/fail_blog/test_main_desktop.py&amp;#x27;, 181, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981da90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4b269250-5a55-45c8-8a93-738afb94b54f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981d790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4b269250-5a55-45c8-8a93-738afb94b54f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981dfa0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/4b269250-5a55-45c8-8a93-738afb94b54f&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f2730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2f015ad8-d7db-42de-9539-25e02b2cce2a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197f2610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2f015ad8-d7db-42de-9539-25e02b2cce2a\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119801e80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/2f015ad8-d7db-42de-9539-25e02b2cce2a&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197e09a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5ebdeaac-a965-408b-aba3-9992696fa56f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197e07f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5ebdeaac-a965-408b-aba3-9992696fa56f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197bd460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5ebdeaac-a965-408b-aba3-9992696fa56f&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197e0c70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/61853c2c-d60e-4673-8be8-7c810daab938\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1197e08e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/61853c2c-d60e-4673-8be8-7c810daab938\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119801fa0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/61853c2c-d60e-4673-8be8-7c810daab938&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981da60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3811f0f5-1b2d-4a23-8dac-23415d834a0e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981d370&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3811f0f5-1b2d-4a23-8dac-23415d834a0e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981dfd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/3811f0f5-1b2d-4a23-8dac-23415d834a0e&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119830d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f03853b3-6b4b-4593-bc07-8258f151e64e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11983f100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f03853b3-6b4b-4593-bc07-8258f151e64e\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11983f280&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f03853b3-6b4b-4593-bc07-8258f151e64e&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981da00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ec2a8c44-6fef-46c4-bdd9-e724864d70c5\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981d310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ec2a8c44-6fef-46c4-bdd9-e724864d70c5\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198012e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ec2a8c44-6fef-46c4-bdd9-e724864d70c5&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:27&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:27&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:327 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11983f070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e6e82e87-6673-4859-8644-b1e4cd996df1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11983f940&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e6e82e87-6673-4859-8644-b1e4cd996df1\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11983f340&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e6e82e87-6673-4859-8644-b1e4cd996df1&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:98 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...cheezdev.com/&amp;#x27; == &amp;#x27;urls.icanhas_stage&amp;#x27;\n  - urls.icanhas_stage\n  + https://icanhas.cheezdev.com/\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119850070&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/da9ad248-6c92-43dd-af2f-6743ba0a1a71\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198502e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/da9ad248-6c92-43dd-af2f-6743ba0a1a71\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119850310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/da9ad248-6c92-43dd-af2f-6743ba0a1a71&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_desktop.py:110 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...ezburger.com/&amp;#x27; == &amp;#x27;icanhas.cheezburger.com/&amp;#x27;\n  - icanhas.cheezburger.com/\n  + https://icanhas.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11983f940&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dfcbaed4-9264-4dea-b0f0-c1cfa9240f55\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198011c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dfcbaed4-9264-4dea-b0f0-c1cfa9240f55\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981df70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/dfcbaed4-9264-4dea-b0f0-c1cfa9240f55&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198509d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ae1d2a48-8993-4725-8ccd-67ad47472798\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119850640&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ae1d2a48-8993-4725-8ccd-67ad47472798\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119850310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/ae1d2a48-8993-4725-8ccd-67ad47472798&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&#34;, &#34;duration&#34;: &#34;00:00:09&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:09&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119860130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/14e4a738-856b-498f-961a-9728121cdd23\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119860730&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/14e4a738-856b-498f-961a-9728121cdd23\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119860700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/14e4a738-856b-498f-961a-9728121cdd23&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_header&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981d5e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7e52542e-3532-495e-9629-f8bbba3b2466\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981d970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7e52542e-3532-495e-9629-f8bbba3b2466\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119801d90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/7e52542e-3532-495e-9629-f8bbba3b2466&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_facebook_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198605b0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/66fa0f5f-9610-47f0-a3ad-1efe8790fdc2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119860610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/66fa0f5f-9610-47f0-a3ad-1efe8790fdc2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119860580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/66fa0f5f-9610-47f0-a3ad-1efe8790fdc2&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&#34;, &#34;duration&#34;: &#34;00:00:08&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_twitter_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:08&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11986e310&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/61fdb80c-4b1f-405a-bcaf-5024cce54953\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11986e580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/61fdb80c-4b1f-405a-bcaf-5024cce54953\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11986e940&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/61fdb80c-4b1f-405a-bcaf-5024cce54953&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&#34;, &#34;duration&#34;: &#34;00:00:10&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_pinterest_footer&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:10&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11983f4f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b488f7e1-a61f-449b-8ebc-d779dd0a4284\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119801ee0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b488f7e1-a61f-449b-8ebc-d779dd0a4284\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11981db80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b488f7e1-a61f-449b-8ebc-d779dd0a4284&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11986e790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f71e74d4-d478-4941-a888-8e12e4401d21\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11986e550&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f71e74d4-d478-4941-a888-8e12e4401d21\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11986ee50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f71e74d4-d478-4941-a888-8e12e4401d21&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119880790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0916b122-2939-426b-b32a-442986270c0f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198807c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0916b122-2939-426b-b32a-442986270c0f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119880d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/0916b122-2939-426b-b32a-442986270c0f&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_submit::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/icanhas/test_main_desktop.py&amp;#x27;, 167, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Skipped&#34;, &#34;testId&#34;: &#34;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&#34;, &#34;duration&#34;: &#34;0 ms&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Skipped&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/desktop/icanhas/test_main_desktop.py::TestMainDesktop::test_redirects_stage::setup&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;0 ms&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;(&amp;#x27;/Users/msb/Documents/Repos/chz-qa-automation/pages/desktop/icanhas/test_main_desktop.py&amp;#x27;, 181, &amp;#x27;Skipped: Test is disabled for now&amp;#x27;)\n&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119860520&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6adce448-6b13-4f5a-bcff-b87d6c97f982\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198607f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6adce448-6b13-4f5a-bcff-b87d6c97f982\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11988a190&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6adce448-6b13-4f5a-bcff-b87d6c97f982&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11986e1f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8f78e423-e3e6-4d57-8b80-ece82e4736bf\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11986e790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8f78e423-e3e6-4d57-8b80-ece82e4736bf\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11986efd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8f78e423-e3e6-4d57-8b80-ece82e4736bf&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119880d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/af3a7471-6d96-48bc-8d0c-d60ae43c7b87\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119880550&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/af3a7471-6d96-48bc-8d0c-d60ae43c7b87\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11988aaf0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/af3a7471-6d96-48bc-8d0c-d60ae43c7b87&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11988a220&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/212e086f-1f8f-487f-af0b-ff788aef2397\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119896100&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/212e086f-1f8f-487f-af0b-ff788aef2397\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119896280&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/212e086f-1f8f-487f-af0b-ff788aef2397&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11988afd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/495fafa8-939b-48e2-a050-1c310cb47154\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11988aa00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/495fafa8-939b-48e2-a050-1c310cb47154\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119880dc0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/495fafa8-939b-48e2-a050-1c310cb47154&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11986e9a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d06dfa14-cadc-48d8-9c6d-f942e968fa09\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198960a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d06dfa14-cadc-48d8-9c6d-f942e968fa09\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119896490&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d06dfa14-cadc-48d8-9c6d-f942e968fa09&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:33&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:33&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:327 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a70d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5d6bbec6-6eba-41eb-991b-9be8ee663407\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a75e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5d6bbec6-6eba-41eb-991b-9be8ee663407\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a74c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/5d6bbec6-6eba-41eb-991b-9be8ee663407&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:34&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:34&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:327 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11988a280&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/afc5d147-22f8-4a70-ac92-cf8f00d78150\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198963a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/afc5d147-22f8-4a70-ac92-cf8f00d78150\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119896160&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/afc5d147-22f8-4a70-ac92-cf8f00d78150&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:97 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...cheezdev.com/&amp;#x27; == &amp;#x27;failblog.cheezdev.com/&amp;#x27;\n  - failblog.cheezdev.com/\n  + https://failblog.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a7ac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/df798a7e-0ab6-443a-ba6b-8c45f8270a96\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a7b20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/df798a7e-0ab6-443a-ba6b-8c45f8270a96\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198b9040&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/df798a7e-0ab6-443a-ba6b-8c45f8270a96&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:109 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://fail...ezburger.com/&amp;#x27; == &amp;#x27;failblog.cheezburger.com/&amp;#x27;\n  - failblog.cheezburger.com/\n  + https://failblog.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a7d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/754a8718-6523-47ea-bd9a-a5d6023c4b3b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a77c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/754a8718-6523-47ea-bd9a-a5d6023c4b3b\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119896760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/754a8718-6523-47ea-bd9a-a5d6023c4b3b&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:121 Assertion failed: Unexpected URL after scrolling up on the page\nassert &amp;#x27;https://fail...cheezdev.com/&amp;#x27; == &amp;#x27;failblog.cheezdev.com/&amp;#x27;\n  - failblog.cheezdev.com/\n  + https://failblog.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198b9970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c787efff-5630-451d-8d05-053c644a6188\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198b9280&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c787efff-5630-451d-8d05-053c644a6188\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198b9790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c787efff-5630-451d-8d05-053c644a6188&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:133 Assertion failed: Unexpected URL after scrolling up on the page\nassert &amp;#x27;https://fail...ezburger.com/&amp;#x27; == &amp;#x27;failblog.cheezburger.com/&amp;#x27;\n  - failblog.cheezburger.com/\n  + https://failblog.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198c63d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e3f51d9f-50be-4613-9519-2cea9bfa0f32\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198c6850&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e3f51d9f-50be-4613-9519-2cea9bfa0f32\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198c6610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e3f51d9f-50be-4613-9519-2cea9bfa0f32&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a7ac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/134c684e-7d8b-48a0-96d1-e7d45e995286\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a7c40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/134c684e-7d8b-48a0-96d1-e7d45e995286\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a7b20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/134c684e-7d8b-48a0-96d1-e7d45e995286&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:15&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:15&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198c6b80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/88c16c58-f8eb-4519-8aa5-8f4fa042fb52\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198c60d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/88c16c58-f8eb-4519-8aa5-8f4fa042fb52\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198c6520&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/88c16c58-f8eb-4519-8aa5-8f4fa042fb52&#34;}], &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/fail_blog/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;----------------------------- Captured stdout call -----------------------------\nError during execution: Message: Unable to locate element: body.mu-ichc.mu-Channel.language-english.mu-theme-light; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5\ndom.find/&amp;lt;/&amp;lt;@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198da580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e9aa7467-ca50-447e-877d-dc0a550129cf\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198dab20&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e9aa7467-ca50-447e-877d-dc0a550129cf\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198da970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/e9aa7467-ca50-447e-877d-dc0a550129cf&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198964c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/efdf8bec-72c9-4dca-af83-a268e8478cd6\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119896f10&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/efdf8bec-72c9-4dca-af83-a268e8478cd6\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198a7cd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/efdf8bec-72c9-4dca-af83-a268e8478cd6&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_open_url_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198dadf0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/989163af-4c3c-47a9-b537-040e0a246aa3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198dad90&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/989163af-4c3c-47a9-b537-040e0a246aa3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198daf40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/989163af-4c3c-47a9-b537-040e0a246aa3&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198e8760&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8079d7c0-c32f-4ee9-a5c2-4f610dc7d6e2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198e8d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8079d7c0-c32f-4ee9-a5c2-4f610dc7d6e2\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198daf70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/8079d7c0-c32f-4ee9-a5c2-4f610dc7d6e2&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&#34;, &#34;duration&#34;: &#34;00:00:06&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_title_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:06&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198b90d0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d9def810-83ce-47fc-864e-0772ebdaafe8\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198e8c40&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d9def810-83ce-47fc-864e-0772ebdaafe8\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198e8130&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d9def810-83ce-47fc-864e-0772ebdaafe8&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198f4340&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d0fe7ed4-d1fd-4d41-b15a-c3cba739419c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198f47f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d0fe7ed4-d1fd-4d41-b15a-c3cba739419c\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198f4580&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/d0fe7ed4-d1fd-4d41-b15a-c3cba739419c&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_ads_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198f4a00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b53bbc90-99b6-497b-926d-7bbd94b51a80\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198f42e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b53bbc90-99b6-497b-926d-7bbd94b51a80\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198f4880&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b53bbc90-99b6-497b-926d-7bbd94b51a80&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&#34;, &#34;duration&#34;: &#34;00:00:13&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:13&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198da280&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6f8bb5b2-096b-4608-a1aa-1e1bbc209b8f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198dadc0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6f8bb5b2-096b-4608-a1aa-1e1bbc209b8f\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1199050a0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/6f8bb5b2-096b-4608-a1aa-1e1bbc209b8f&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&#34;, &#34;duration&#34;: &#34;00:00:34&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_login_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:34&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:global_functions.py:327 Error: tuple index out of range\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119905880&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/66c2381e-3e05-4caa-8d46-268b7224bec3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119905fd0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/66c2381e-3e05-4caa-8d46-268b7224bec3\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119905e80&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/66c2381e-3e05-4caa-8d46-268b7224bec3&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&#34;, &#34;duration&#34;: &#34;00:00:04&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:04&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:97 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...cheezdev.com/&amp;#x27; == &amp;#x27;icanhas.cheezdev.com/&amp;#x27;\n  - icanhas.cheezdev.com/\n  + https://icanhas.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198e8d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/92884522-83c7-4a50-9910-79e24a4c8121\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198f4790&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/92884522-83c7-4a50-9910-79e24a4c8121\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x1198f42e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/92884522-83c7-4a50-9910-79e24a4c8121&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_down_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:109 Assertion failed: Unexpected URL after scrolling down on the page\nassert &amp;#x27;https://ican...ezburger.com/&amp;#x27; == &amp;#x27;icanhas.cheezburger.com/&amp;#x27;\n  - icanhas.cheezburger.com/\n  + https://icanhas.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11990f4c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f0d99b7b-a418-41f9-b6f4-5e3d61a69244\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11990f940&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f0d99b7b-a418-41f9-b6f4-5e3d61a69244\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11990f700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/f0d99b7b-a418-41f9-b6f4-5e3d61a69244&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:123 Assertion failed: URL inesperada despu\u00e9s de desplazarse hacia arriba en la p\u00e1gina \nassert &amp;#x27;https://ican...cheezdev.com/&amp;#x27; == &amp;#x27;icanhas.cheezdev.com/&amp;#x27;\n  - icanhas.cheezdev.com/\n  + https://icanhas.cheezdev.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11990fa60&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c8fb062a-0428-499c-97f6-9cc200eb85cd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11990fac0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c8fb062a-0428-499c-97f6-9cc200eb85cd\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11990f610&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/c8fb062a-0428-499c-97f6-9cc200eb85cd&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&#34;, &#34;duration&#34;: &#34;00:00:05&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_scroll_up_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:05&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;------------------------------ Captured log call -------------------------------\nWARNING  root:test_main_mobile.py:137 Assertion failed: URL inesperada despu\u00e9s de desplazarse hacia arriba en la p\u00e1gina \nassert &amp;#x27;https://ican...ezburger.com/&amp;#x27; == &amp;#x27;icanhas.cheezburger.com/&amp;#x27;\n  - icanhas.cheezburger.com/\n  + https://icanhas.cheezburger.com/\n  ? ++++++++\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11991e2e0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/20551cbb-c11b-4ab2-819e-c3e19eb00bce\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11991e1c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/20551cbb-c11b-4ab2-819e-c3e19eb00bce\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11991e430&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/20551cbb-c11b-4ab2-819e-c3e19eb00bce&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_stage&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11991e1c0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/816e7396-7434-409b-af44-0ac5da5fc6e8\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11991e700&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/816e7396-7434-409b-af44-0ac5da5fc6e8\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11991e460&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/816e7396-7434-409b-af44-0ac5da5fc6e8&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&#34;, &#34;duration&#34;: &#34;00:00:14&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_mu_mosaic_prod&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:14&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;No log output captured.---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11990f4f0&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b2eeedd8-38ee-49b2-a6e0-4f363c81e2ce\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x11990fb50&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b2eeedd8-38ee-49b2-a6e0-4f363c81e2ce\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119932190&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/b2eeedd8-38ee-49b2-a6e0-4f363c81e2ce&#34;}], &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;: [{&#34;extras&#34;: [], &#34;result&#34;: &#34;Passed&#34;, &#34;testId&#34;: &#34;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&#34;, &#34;duration&#34;: &#34;00:00:07&#34;, &#34;resultsTableRow&#34;: [&#34;&lt;td class=\&#34;col-result\&#34;&gt;Passed&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-testId\&#34;&gt;pages/mobile/icanhas/test_main_mobile.py::TestMainMobile::test_toggle_display_theme&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-duration\&#34;&gt;00:00:07&lt;/td&gt;&#34;, &#34;&lt;td class=\&#34;col-links\&#34;&gt;&lt;/td&gt;&#34;], &#34;log&#34;: &#34;----------------------------- Captured stdout call -----------------------------\nError during execution: Message: Element &amp;lt;button class=&amp;quot;mu-btn mu-theme-btn mu-script&amp;quot;&amp;gt; is not clickable at point (432,21) because another element &amp;lt;div class=&amp;quot;pushly_popover-message-headline pushly-prompt-message-headline&amp;quot;&amp;gt; obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:335:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:176:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:135:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:204:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:84:31\n\n---------------------------- Captured log teardown -----------------------------\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119932970&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/39eee866-dbd4-45b7-9744-7a7f01700891\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119932f70&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/39eee866-dbd4-45b7-9744-7a7f01700891\nWARNING  urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by &amp;#x27;NewConnectionError(&amp;#x27;&amp;lt;urllib3.connection.HTTPConnection object at 0x119932d00&amp;gt;: Failed to establish a new connection: [Errno 61] Connection refused&amp;#x27;)&amp;#x27;: /session/39eee866-dbd4-45b7-9744-7a7f01700891&#34;}]}, &#34;renderCollapsed&#34;: [&#34;passed&#34;], &#34;initialSort&#34;: &#34;result&#34;, &#34;title&#34;: &#34;chz.html&#34;}"></div>
    <script>
      (function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
const { getCollapsedCategory, setCollapsedIds } = require('./storage.js')

class DataManager {
    setManager(data) {
        const collapsedCategories = [...getCollapsedCategory(data.renderCollapsed)]
        const collapsedIds = []
        const tests = Object.values(data.tests).flat().map((test, index) => {
            const collapsed = collapsedCategories.includes(test.result.toLowerCase())
            const id = `test_${index}`
            if (collapsed) {
                collapsedIds.push(id)
            }
            return {
                ...test,
                id,
                collapsed,
            }
        })
        const dataBlob = { ...data, tests }
        this.data = { ...dataBlob }
        this.renderData = { ...dataBlob }
        setCollapsedIds(collapsedIds)
    }

    get allData() {
        return { ...this.data }
    }

    resetRender() {
        this.renderData = { ...this.data }
    }

    setRender(data) {
        this.renderData.tests = [...data]
    }

    toggleCollapsedItem(id) {
        this.renderData.tests = this.renderData.tests.map((test) =>
            test.id === id ? { ...test, collapsed: !test.collapsed } : test,
        )
    }

    set allCollapsed(collapsed) {
        this.renderData = { ...this.renderData, tests: [...this.renderData.tests.map((test) => (
            { ...test, collapsed }
        ))] }
    }

    get testSubset() {
        return [...this.renderData.tests]
    }

    get environment() {
        return this.renderData.environment
    }

    get initialSort() {
        return this.data.initialSort
    }
}

module.exports = {
    manager: new DataManager(),
}

},{"./storage.js":8}],2:[function(require,module,exports){
const mediaViewer = require('./mediaviewer.js')
const templateEnvRow = document.getElementById('template_environment_row')
const templateResult = document.getElementById('template_results-table__tbody')

function htmlToElements(html) {
    const temp = document.createElement('template')
    temp.innerHTML = html
    return temp.content.childNodes
}

const find = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return elem.querySelector(selector)
}

const findAll = (selector, elem) => {
    if (!elem) {
        elem = document
    }
    return [...elem.querySelectorAll(selector)]
}

const dom = {
    getStaticRow: (key, value) => {
        const envRow = templateEnvRow.content.cloneNode(true)
        const isObj = typeof value === 'object' && value !== null
        const values = isObj ? Object.keys(value).map((k) => `${k}: ${value[k]}`) : null

        const valuesElement = htmlToElements(
            values ? `<ul>${values.map((val) => `<li>${val}</li>`).join('')}<ul>` : `<div>${value}</div>`)[0]
        const td = findAll('td', envRow)
        td[0].textContent = key
        td[1].appendChild(valuesElement)

        return envRow
    },
    getResultTBody: ({ testId, id, log, extras, resultsTableRow, tableHtml, result, collapsed }) => {
        const resultBody = templateResult.content.cloneNode(true)
        resultBody.querySelector('tbody').classList.add(result.toLowerCase())
        resultBody.querySelector('tbody').id = testId
        resultBody.querySelector('.collapsible').dataset.id = id

        resultsTableRow.forEach((html) => {
            const t = document.createElement('template')
            t.innerHTML = html
            resultBody.querySelector('.collapsible').appendChild(t.content)
        })

        if (log) {
            // Wrap lines starting with "E" with span.error to color those lines red
            const wrappedLog = log.replace(/^E.*$/gm, (match) => `<span class="error">${match}</span>`)
            resultBody.querySelector('.log').innerHTML = wrappedLog
        } else {
            resultBody.querySelector('.log').remove()
        }

        if (collapsed) {
            resultBody.querySelector('.collapsible > td')?.classList.add('collapsed')
            resultBody.querySelector('.extras-row').classList.add('hidden')
        } else {
            resultBody.querySelector('.collapsible > td')?.classList.remove('collapsed')
        }

        const media = []
        extras?.forEach(({ name, format_type, content }) => {
            if (['image', 'video'].includes(format_type)) {
                media.push({ path: content, name, format_type })
            }

            if (format_type === 'html') {
                resultBody.querySelector('.extraHTML').insertAdjacentHTML('beforeend', `<div>${content}</div>`)
            }
        })
        mediaViewer.setup(resultBody, media)

        // Add custom html from the pytest_html_results_table_html hook
        tableHtml?.forEach((item) => {
            resultBody.querySelector('td[class="extra"]').insertAdjacentHTML('beforeend', item)
        })

        return resultBody
    },
}

module.exports = {
    dom,
    htmlToElements,
    find,
    findAll,
}

},{"./mediaviewer.js":6}],3:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const storageModule = require('./storage.js')

const getFilteredSubSet = (filter) =>
    manager.allData.tests.filter(({ result }) => filter.includes(result.toLowerCase()))

const doInitFilter = () => {
    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)
}

const doFilter = (type, show) => {
    if (show) {
        storageModule.showCategory(type)
    } else {
        storageModule.hideCategory(type)
    }

    const currentFilter = storageModule.getVisible()
    const filteredSubset = getFilteredSubSet(currentFilter)
    manager.setRender(filteredSubset)

    const sortColumn = storageModule.getSort()
    doSort(sortColumn, true)
}

module.exports = {
    doFilter,
    doInitFilter,
}

},{"./datamanager.js":1,"./sort.js":7,"./storage.js":8}],4:[function(require,module,exports){
const { redraw, bindEvents, renderStatic } = require('./main.js')
const { doInitFilter } = require('./filter.js')
const { doInitSort } = require('./sort.js')
const { manager } = require('./datamanager.js')
const data = JSON.parse(document.getElementById('data-container').dataset.jsonblob)

function init() {
    manager.setManager(data)
    doInitFilter()
    doInitSort()
    renderStatic()
    redraw()
    bindEvents()
}

init()

},{"./datamanager.js":1,"./filter.js":3,"./main.js":5,"./sort.js":7}],5:[function(require,module,exports){
const { dom, find, findAll } = require('./dom.js')
const { manager } = require('./datamanager.js')
const { doSort } = require('./sort.js')
const { doFilter } = require('./filter.js')
const {
    getVisible,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    getSortDirection,
    possibleFilters,
} = require('./storage.js')

const removeChildren = (node) => {
    while (node.firstChild) {
        node.removeChild(node.firstChild)
    }
}

const renderStatic = () => {
    const renderEnvironmentTable = () => {
        const environment = manager.environment
        const rows = Object.keys(environment).map((key) => dom.getStaticRow(key, environment[key]))
        const table = document.getElementById('environment')
        removeChildren(table)
        rows.forEach((row) => table.appendChild(row))
    }
    renderEnvironmentTable()
}

const addItemToggleListener = (elem) => {
    elem.addEventListener('click', ({ target }) => {
        const id = target.parentElement.dataset.id
        manager.toggleCollapsedItem(id)

        const collapsedIds = getCollapsedIds()
        if (collapsedIds.includes(id)) {
            const updated = collapsedIds.filter((item) => item !== id)
            setCollapsedIds(updated)
        } else {
            collapsedIds.push(id)
            setCollapsedIds(collapsedIds)
        }
        redraw()
    })
}

const renderContent = (tests) => {
    const sortAttr = getSort(manager.initialSort)
    const sortAsc = JSON.parse(getSortDirection())
    const rows = tests.map(dom.getResultTBody)
    const table = document.getElementById('results-table')
    const tableHeader = document.getElementById('results-table-head')

    const newTable = document.createElement('table')
    newTable.id = 'results-table'

    // remove all sorting classes and set the relevant
    findAll('.sortable', tableHeader).forEach((elem) => elem.classList.remove('asc', 'desc'))
    tableHeader.querySelector(`.sortable[data-column-type="${sortAttr}"]`)?.classList.add(sortAsc ? 'desc' : 'asc')
    newTable.appendChild(tableHeader)

    if (!rows.length) {
        const emptyTable = document.getElementById('template_results-table__body--empty').content.cloneNode(true)
        newTable.appendChild(emptyTable)
    } else {
        rows.forEach((row) => {
            if (!!row) {
                findAll('.collapsible td:not(.col-links', row).forEach(addItemToggleListener)
                find('.logexpander', row).addEventListener('click',
                    (evt) => evt.target.parentNode.classList.toggle('expanded'),
                )
                newTable.appendChild(row)
            }
        })
    }

    table.replaceWith(newTable)
}

const renderDerived = () => {
    const currentFilter = getVisible()
    possibleFilters.forEach((result) => {
        const input = document.querySelector(`input[data-test-result="${result}"]`)
        input.checked = currentFilter.includes(result)
    })
}

const bindEvents = () => {
    const filterColumn = (evt) => {
        const { target: element } = evt
        const { testResult } = element.dataset

        doFilter(testResult, element.checked)
        const collapsedIds = getCollapsedIds()
        const updated = manager.renderData.tests.map((test) => {
            return {
                ...test,
                collapsed: collapsedIds.includes(test.id),
            }
        })
        manager.setRender(updated)
        redraw()
    }

    const header = document.getElementById('environment-header')
    header.addEventListener('click', () => {
        const table = document.getElementById('environment')
        table.classList.toggle('hidden')
        header.classList.toggle('collapsed')
    })

    findAll('input[name="filter_checkbox"]').forEach((elem) => {
        elem.addEventListener('click', filterColumn)
    })

    findAll('.sortable').forEach((elem) => {
        elem.addEventListener('click', (evt) => {
            const { target: element } = evt
            const { columnType } = element.dataset
            doSort(columnType)
            redraw()
        })
    })

    document.getElementById('show_all_details').addEventListener('click', () => {
        manager.allCollapsed = false
        setCollapsedIds([])
        redraw()
    })
    document.getElementById('hide_all_details').addEventListener('click', () => {
        manager.allCollapsed = true
        const allIds = manager.renderData.tests.map((test) => test.id)
        setCollapsedIds(allIds)
        redraw()
    })
}

const redraw = () => {
    const { testSubset } = manager

    renderContent(testSubset)
    renderDerived()
}

module.exports = {
    redraw,
    bindEvents,
    renderStatic,
}

},{"./datamanager.js":1,"./dom.js":2,"./filter.js":3,"./sort.js":7,"./storage.js":8}],6:[function(require,module,exports){
class MediaViewer {
    constructor(assets) {
        this.assets = assets
        this.index = 0
    }

    nextActive() {
        this.index = this.index === this.assets.length - 1 ? 0 : this.index + 1
        return [this.activeFile, this.index]
    }

    prevActive() {
        this.index = this.index === 0 ? this.assets.length - 1 : this.index -1
        return [this.activeFile, this.index]
    }

    get currentIndex() {
        return this.index
    }

    get activeFile() {
        return this.assets[this.index]
    }
}


const setup = (resultBody, assets) => {
    if (!assets.length) {
        resultBody.querySelector('.media').classList.add('hidden')
        return
    }

    const mediaViewer = new MediaViewer(assets)
    const container = resultBody.querySelector('.media-container')
    const leftArrow = resultBody.querySelector('.media-container__nav--left')
    const rightArrow = resultBody.querySelector('.media-container__nav--right')
    const mediaName = resultBody.querySelector('.media__name')
    const counter = resultBody.querySelector('.media__counter')
    const imageEl = resultBody.querySelector('img')
    const sourceEl = resultBody.querySelector('source')
    const videoEl = resultBody.querySelector('video')

    const setImg = (media, index) => {
        if (media?.format_type === 'image') {
            imageEl.src = media.path

            imageEl.classList.remove('hidden')
            videoEl.classList.add('hidden')
        } else if (media?.format_type === 'video') {
            sourceEl.src = media.path

            videoEl.classList.remove('hidden')
            imageEl.classList.add('hidden')
        }

        mediaName.innerText = media?.name
        counter.innerText = `${index + 1} / ${assets.length}`
    }
    setImg(mediaViewer.activeFile, mediaViewer.currentIndex)

    const moveLeft = () => {
        const [media, index] = mediaViewer.prevActive()
        setImg(media, index)
    }
    const doRight = () => {
        const [media, index] = mediaViewer.nextActive()
        setImg(media, index)
    }
    const openImg = () => {
        window.open(mediaViewer.activeFile.path, '_blank')
    }
    if (assets.length === 1) {
        container.classList.add('media-container--fullscreen')
    } else {
        leftArrow.addEventListener('click', moveLeft)
        rightArrow.addEventListener('click', doRight)
    }
    imageEl.addEventListener('click', openImg)
}

module.exports = {
    setup,
}

},{}],7:[function(require,module,exports){
const { manager } = require('./datamanager.js')
const storageModule = require('./storage.js')

const genericSort = (list, key, ascending, customOrder) => {
    let sorted
    if (customOrder) {
        sorted = list.sort((a, b) => {
            const aValue = a.result.toLowerCase()
            const bValue = b.result.toLowerCase()

            const aIndex = customOrder.findIndex((item) => item.toLowerCase() === aValue)
            const bIndex = customOrder.findIndex((item) => item.toLowerCase() === bValue)

            // Compare the indices to determine the sort order
            return aIndex - bIndex
        })
    } else {
        sorted = list.sort((a, b) => a[key] === b[key] ? 0 : a[key] > b[key] ? 1 : -1)
    }

    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const durationSort = (list, ascending) => {
    const parseDuration = (duration) => {
        if (duration.includes(':')) {
            // If it's in the format "HH:mm:ss"
            const [hours, minutes, seconds] = duration.split(':').map(Number)
            return (hours * 3600 + minutes * 60 + seconds) * 1000
        } else {
            // If it's in the format "nnn ms"
            return parseInt(duration)
        }
    }
    const sorted = list.sort((a, b) => parseDuration(a['duration']) - parseDuration(b['duration']))
    if (ascending) {
        sorted.reverse()
    }
    return sorted
}

const doInitSort = () => {
    const type = storageModule.getSort(manager.initialSort)
    const ascending = storageModule.getSortDirection()
    const list = manager.testSubset
    const initialOrder = ['Error', 'Failed', 'Rerun', 'XFailed', 'XPassed', 'Skipped', 'Passed']

    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    if (type?.toLowerCase() === 'original') {
        manager.setRender(list)
    } else {
        let sortedList
        switch (type) {
        case 'duration':
            sortedList = durationSort(list, ascending)
            break
        case 'result':
            sortedList = genericSort(list, type, ascending, initialOrder)
            break
        default:
            sortedList = genericSort(list, type, ascending)
            break
        }
        manager.setRender(sortedList)
    }
}

const doSort = (type, skipDirection) => {
    const newSortType = storageModule.getSort(manager.initialSort) !== type
    const currentAsc = storageModule.getSortDirection()
    let ascending
    if (skipDirection) {
        ascending = currentAsc
    } else {
        ascending = newSortType ? false : !currentAsc
    }
    storageModule.setSort(type)
    storageModule.setSortDirection(ascending)

    const list = manager.testSubset
    const sortedList = type === 'duration' ? durationSort(list, ascending) : genericSort(list, type, ascending)
    manager.setRender(sortedList)
}

module.exports = {
    doInitSort,
    doSort,
}

},{"./datamanager.js":1,"./storage.js":8}],8:[function(require,module,exports){
const possibleFilters = [
    'passed',
    'skipped',
    'failed',
    'error',
    'xfailed',
    'xpassed',
    'rerun',
]

const getVisible = () => {
    const url = new URL(window.location.href)
    const settings = new URLSearchParams(url.search).get('visible')
    const lower = (item) => {
        const lowerItem = item.toLowerCase()
        if (possibleFilters.includes(lowerItem)) {
            return lowerItem
        }
        return null
    }
    return settings === null ?
        possibleFilters :
        [...new Set(settings?.split(',').map(lower).filter((item) => item))]
}

const hideCategory = (categoryToHide) => {
    const url = new URL(window.location.href)
    const visibleParams = new URLSearchParams(url.search).get('visible')
    const currentVisible = visibleParams ? visibleParams.split(',') : [...possibleFilters]
    const settings = [...new Set(currentVisible)].filter((f) => f !== categoryToHide).join(',')

    url.searchParams.set('visible', settings)
    window.history.pushState({}, null, unescape(url.href))
}

const showCategory = (categoryToShow) => {
    if (typeof window === 'undefined') {
        return
    }
    const url = new URL(window.location.href)
    const currentVisible = new URLSearchParams(url.search).get('visible')?.split(',').filter(Boolean) ||
        [...possibleFilters]
    const settings = [...new Set([categoryToShow, ...currentVisible])]
    const noFilter = possibleFilters.length === settings.length || !settings.length

    noFilter ? url.searchParams.delete('visible') : url.searchParams.set('visible', settings.join(','))
    window.history.pushState({}, null, unescape(url.href))
}

const getSort = (initialSort) => {
    const url = new URL(window.location.href)
    let sort = new URLSearchParams(url.search).get('sort')
    if (!sort) {
        sort = initialSort || 'result'
    }
    return sort
}

const setSort = (type) => {
    const url = new URL(window.location.href)
    url.searchParams.set('sort', type)
    window.history.pushState({}, null, unescape(url.href))
}

const getCollapsedCategory = (renderCollapsed) => {
    let categories
    if (typeof window !== 'undefined') {
        const url = new URL(window.location.href)
        const collapsedItems = new URLSearchParams(url.search).get('collapsed')
        switch (true) {
        case !renderCollapsed && collapsedItems === null:
            categories = ['passed']
            break
        case collapsedItems?.length === 0 || /^["']{2}$/.test(collapsedItems):
            categories = []
            break
        case /^all$/.test(collapsedItems) || collapsedItems === null && /^all$/.test(renderCollapsed):
            categories = [...possibleFilters]
            break
        default:
            categories = collapsedItems?.split(',').map((item) => item.toLowerCase()) || renderCollapsed
            break
        }
    } else {
        categories = []
    }
    return categories
}

const getSortDirection = () => JSON.parse(sessionStorage.getItem('sortAsc')) || false
const setSortDirection = (ascending) => sessionStorage.setItem('sortAsc', ascending)

const getCollapsedIds = () => JSON.parse(sessionStorage.getItem('collapsedIds')) || []
const setCollapsedIds = (list) => sessionStorage.setItem('collapsedIds', JSON.stringify(list))

module.exports = {
    getVisible,
    hideCategory,
    showCategory,
    getCollapsedIds,
    setCollapsedIds,
    getSort,
    setSort,
    getSortDirection,
    setSortDirection,
    getCollapsedCategory,
    possibleFilters,
}

},{}]},{},[4]);
    </script>
  </footer>
</html>